import {
  B, BY, C, COMMENT, D, DISABLED, DYN, E, ENABLE_DISABLE, F, I, INVALID, N, NAME, ORDERED, S,
  type EndpointDef, type FieldDef,
} from '../types';

/**
 * Networking menus: interfaces & switching, IPv4/IPv6, firewall, routing, queues, MPLS.
 * Fields are descriptive metadata — the UI adapts to whatever the device actually returns.
 */

const ruleTarget = [
  S('chain', { key: true, required: true as boolean, mono: true, primary: true as boolean }),
];

/* ============================= INTERFACES ============================= */

const interfaceFields: FieldDef[] = [
  NAME,
  S('type', { width: 'sm', mono: true }),
  S('mtu', { width: 'xs', mono: true }),
  S('l2mtu', { width: 'xs', mono: true }),
  S('mac-address', { label: 'MAC', mono: true, width: 'sm' }),
  S('rx-byte', { type: 'bytes', key: true }),
  S('tx-byte', { type: 'bytes', key: true }),
  E('arp', ['enabled', 'disabled', 'proxy-arp', 'reply-only'], { advanced: false }),
  D('arp-timeout', { advanced: true }),
  DISABLED,
  { name: 'running', type: 'boolean', tone: 'success', key: true, boolLabels: ['running', 'down'], label: 'State' },
  { name: 'slave', type: 'boolean', label: 'Slave' },
  COMMENT,
  S('last-link-up-time', { advanced: true }),
];

export const interfaceEndpoints: EndpointDef[] = [
  {
    path: 'interface', label: 'Interfaces', category: 'interfaces', group: 'Interfaces', key: true, ordered: false,
    icon: 'Network', availability: 'core', demoRows: 12,
    description: 'Every logical interface on the device: ethernet, bridge, VLAN, tunnels, wireless, PPP.',
    fields: interfaceFields, live: ['rx-byte', 'tx-byte'],
    commands: [
      ...ENABLE_DISABLE,
      { id: 'monitor-traffic', label: 'Monitor traffic', icon: 'Activity', path: 'monitor-traffic', target: 'name', body: { once: '' }, response: 'json' },
      { id: 'reset-counters', label: 'Reset counters', icon: 'RotateCcw', path: 'reset-counters', target: 'name' },
    ],
  },
  {
    path: 'interface/ethernet', label: 'Ethernet', category: 'interfaces', group: 'Interfaces', key: true,
    icon: 'Cable', demoRows: 8,
    description: 'Physical ports: speed, duplex, flow control, POE and cable diagnostics.',
    fields: [
      NAME,
      { name: 'mac-address', type: 'mac', label: 'MAC', mono: true, key: true },
      { name: 'auto-negotiation', type: 'boolean', label: 'Auto negotiation', key: true },
      { name: 'advertise', type: 'string', key: true },
      { name: 'speed', type: 'string', label: 'Speed', key: true, mono: true },
      { name: 'full-duplex', type: 'boolean', label: 'Full duplex', key: true, boolLabels: ['full', 'half'] },
      S('mtu'), S('l2mtu', { advanced: true }),
      S('tx-flow-control', { key: true }), S('rx-flow-control', { key: true }),
      B('poe-out', { label: 'PoE out', advanced: true }),
      B('running', { tone: 'success', label: 'Link', key: true, boolLabels: ['up', 'down'] }),
      COMMENT,
    ],
    commands: [
      { id: 'monitor', label: 'Monitor', icon: 'Activity', path: 'monitor', target: 'name', body: { once: '' }, response: 'json' },
      { id: 'reset-counters', label: 'Reset counters', icon: 'RotateCcw', path: 'reset-counters', target: 'name' },
      { id: 'cable-test', label: 'Cable test', icon: 'Wrench', path: 'cable-test', target: 'name', body: { once: '' }, response: 'json' },
    ],
  },
  {
    path: 'interface/bridge', label: 'Bridges', category: 'interfaces', group: 'Switching', key: true, icon: 'Waypoints', demoRows: 3,
    description: 'Software bridges, their ports, VLAN tables and host/MDB tables.',
    fields: [
      NAME, S('mtu', { key: true }), S('l2mtu'), { name: 'mac-address', type: 'mac', label: 'MAC', mono: true, key: true },
      E('protocol-mode', ['none', 'rstp', 'mstp'], { key: true, default: 'rstp' }),
      S('vlan-filtering', { type: 'boolean', key: true } as FieldDef),
      N('priority', { advanced: true }), B('igmp-snooping', { advanced: true }), DISABLED, COMMENT,
    ],
    commands: ENABLE_DISABLE,
  },
  {
    path: 'interface/bridge/port', label: 'Bridge Ports', category: 'interfaces', group: 'Switching', icon: 'Plug', demoRows: 6,
    fields: [
      S('interface', { key: true, primary: true, mono: true, required: true }),
      S('bridge', { key: true, mono: true, required: true }),
      E('pvid', ['1'], { type: 'number', advanced: true, default: 1 }),
      S('frame-types', { key: true }), S('ingress-filtering', { type: 'boolean', key: true } as FieldDef),
      N('priority', { advanced: true }), N('path-cost', { advanced: true }), DISABLED, COMMENT,
    ],
    commands: ENABLE_DISABLE,
  },
  {
    path: 'interface/bridge/vlan', label: 'Bridge VLANs', category: 'interfaces', group: 'Switching', icon: 'Layers', demoRows: 4,
    fields: [
      S('bridge', { key: true, mono: true, required: true }),
      S('vlan-ids', { label: 'VLAN IDs', key: true, primary: true, mono: true, required: true, placeholder: '10,20,30' }),
      S('tagged', { key: true, mono: true }), S('untagged', { key: true, mono: true }),
      B('dynamic', { label: 'Dynamic' }), DISABLED, COMMENT,
    ],
  },
  {
    path: 'interface/bridge/settings', label: 'Bridge Settings', category: 'interfaces', group: 'Switching', kind: 'singleton', icon: 'Settings2',
    fields: [
      B('use-ip-firewall'), B('use-ip-firewall-for-vlan', { advanced: true }), B('allow-fast-path'), B('ether-type'),
      S('frame-types'), D('forward-delay'), D('max-message-age'), D('hello-time'), N('priority', { advanced: true }),
      B('igmp-snooping', { advanced: true }), D('igmp-version'), S('dhcp-snooping', { advanced: true }),
    ],
  },
  {
    path: 'interface/bridge/host', label: 'Bridge Hosts', category: 'interfaces', group: 'Switching', readOnly: true, icon: 'Table2', demoRows: 10,
    fields: [
      { name: 'mac-address', type: 'mac', label: 'MAC', mono: true, key: true, primary: true },
      S('bridge', { key: true, mono: true }), S('on-interface', { key: true, mono: true }),
      { name: 'dynamic', type: 'readonly', key: true }, S('age'),
    ],
  },
  {
    path: 'interface/bridge/mdb', label: 'Multicast DB', category: 'interfaces', group: 'Switching', readOnly: true, icon: 'Radio', demoRows: 5,
    fields: [
      S('bridge', { key: true }), S('mac-address', { key: true, mono: true }), S('port', { key: true }),
      S('group', { key: true }), S('vid', { key: true }), S('on-interface'),
    ],
  },
  {
    path: 'interface/vlan', label: 'VLANs', category: 'interfaces', group: 'Interfaces', key: true, icon: 'Layers', demoRows: 6,
    fields: [
      NAME, S('interface', { key: true, mono: true, required: true }),
      N('vlan-id', { label: 'VLAN ID', key: true, required: true, primary: true }),
      S('mtu', { key: true }), B('use-service-tag', { advanced: true }), DISABLED, COMMENT,
    ],
    commands: ENABLE_DISABLE,
  },
  {
    path: 'interface/bonding', label: 'Bonding', category: 'interfaces', group: 'Interfaces', icon: 'Link2', demoRows: 2,
    fields: [
      NAME, S('slaves', { key: true, mono: true }), S('mode', { key: true }), S('transmit-hash-policy', { key: true }),
      S('mtu'), S('lacp-rate', { advanced: true }), B('lacp-user-key', { advanced: true }), D('link-monitoring'),
      D('arp-interval', { advanced: true }), S('arp-ip-targets', { advanced: true, mono: true }), S('primary', { advanced: true }),
      N('min-links', { advanced: true }), DISABLED, COMMENT,
    ],
    commands: ENABLE_DISABLE,
  },
  {
    path: 'interface/vrrp', label: 'VRRP', category: 'interfaces', group: 'Interfaces', icon: 'Shield', demoRows: 2,
    fields: [
      NAME, S('interface', { key: true }), N('vrid', { key: true }), I('priority', {}),
      S('version', { key: true }), D('interval'), B('preemption-mode', { advanced: true }), S('authentication', { advanced: true }),
      B('on-backup', { advanced: true }), B('on-master', { advanced: true }), DISABLED, COMMENT,
    ],
  },
  {
    path: 'interface/vxlan', label: 'VXLAN', category: 'interfaces', group: 'Tunnels', icon: 'Boxes', availability: 'v7', demoRows: 1,
    fields: [
      NAME, S('vni', { key: true }), S('remote-ip', { key: true, mono: true }), S('local-address', { key: true, mono: true }),
      N('port', { advanced: true }), N('mtu'), B('vtv', { advanced: true }), DISABLED, COMMENT,
    ],
    commands: ENABLE_DISABLE,
  },
  {
    path: 'interface/eoip', label: 'EoIP', category: 'interfaces', group: 'Tunnels', icon: 'Cable', demoRows: 1,
    fields: [
      NAME, S('remote-address', { key: true, mono: true, required: true }), N('tunnel-id', { key: true, required: true }),
      S('local-address', { mono: true }), B('keepalive'), D('keepalive-timeout', { advanced: true }), B('dont-fragment', { advanced: true }),
      S('clamp-tcp-mss', { advanced: true }), S('ipsec-secret', { advanced: true }), DISABLED, COMMENT,
    ],
    commands: ENABLE_DISABLE,
  },
  {
    path: 'interface/gre', label: 'GRE', category: 'interfaces', group: 'Tunnels', icon: 'Cable', demoRows: 1,
    fields: [
      NAME, S('remote-address', { key: true, mono: true, required: true }), S('local-address', { mono: true }),
      B('keepalive'), D('keepalive-timeout', { advanced: true }), S('dont-fragment', { advanced: true }),
      S('clamp-tcp-mss', { advanced: true }), S('ipsec-secret', { advanced: true }), DISABLED, COMMENT,
    ],
    commands: ENABLE_DISABLE,
  },
  { path: 'interface/gre6', label: 'GRE6', category: 'interfaces', group: 'Tunnels', icon: 'Cable', availability: 'v7', demoRows: 0,
    fields: [NAME, S('remote-address', { key: true, mono: true }), S('local-address', { mono: true }), B('keepalive'), D('keepalive-timeout', { advanced: true }), DISABLED, COMMENT],
    commands: ENABLE_DISABLE },
  { path: 'interface/ipip', label: 'IPIP', category: 'interfaces', group: 'Tunnels', icon: 'Cable', demoRows: 0,
    fields: [NAME, S('remote-address', { key: true, mono: true }), S('local-address', { mono: true }), B('keepalive'), D('keepalive-timeout', { advanced: true }), S('ipsec-secret', { advanced: true }), DISABLED, COMMENT],
    commands: ENABLE_DISABLE },
  { path: 'interface/ipipv6', label: 'IPIPv6', category: 'interfaces', group: 'Tunnels', icon: 'Cable', availability: 'optional', demoRows: 0,
    fields: [NAME, S('remote-address', { key: true, mono: true }), S('local-address', { mono: true }), B('keepalive'), DISABLED, COMMENT] },
  { path: 'interface/6to4', label: '6to4', category: 'interfaces', group: 'Tunnels', icon: 'Cable', availability: 'optional', demoRows: 0,
    fields: [NAME, S('remote-address', { key: true }), S('local-address'), S('mtu'), B('keepalive'), DISABLED, COMMENT] },
  { path: 'interface/l2tp-ether', label: 'L2TP Ether', category: 'interfaces', group: 'Tunnels', icon: 'Cable', availability: 'optional', demoRows: 0,
    fields: [NAME, S('session', { key: true }), S('peer', { key: true }), S('local-address'), DISABLED, COMMENT] },
  {
    path: 'interface/lte', label: 'LTE', category: 'interfaces', group: 'Interfaces', icon: 'Signal', availability: 'v7', demoRows: 1,
    description: 'LTE/5G modems with live signal monitoring and AT command access.',
    fields: [
      NAME, S('apn-profiles', { key: true }), S('network-mode', { key: true }), S('pin', { advanced: true }),
      S('data-class', { advanced: true }), B('sms-read', { advanced: true }), S('mtu'), N('operator', { advanced: true }),
      DISABLED, COMMENT,
    ],
    commands: [
      ...ENABLE_DISABLE,
      { id: 'monitor', label: 'Monitor', icon: 'Activity', path: 'monitor', target: 'name', body: { once: '' }, response: 'json' },
      { id: 'at-chat', label: 'AT chat', icon: 'Terminal', path: 'at-chat', target: 'name', params: [{ name: 'input', label: 'AT command', type: 'string', placeholder: 'AT+CSQ' }], response: 'json' },
      { id: 'firmware-upgrade', label: 'Firmware upgrade', icon: 'Download', path: 'firmware-upgrade', target: 'name', danger: true },
    ],
  },
  { path: 'interface/macsec', label: 'MACsec', category: 'interfaces', group: 'Interfaces', icon: 'Lock', availability: 'v7.16', demoRows: 0,
    fields: [NAME, S('interface', { key: true }), S('profile', { key: true }), DISABLED, COMMENT] },
  {
    path: 'interface/list', label: 'Interface Lists', category: 'interfaces', group: 'Lists & Detection', icon: 'List', demoRows: 3,
    fields: [NAME, B('dynamic'), B('include-all', { advanced: true }), COMMENT],
  },
  {
    path: 'interface/list/member', label: 'List Members', category: 'interfaces', group: 'Lists & Detection', icon: 'ListPlus', demoRows: 6,
    fields: [
      S('list', { key: true, mono: true, required: true }), S('interface', { key: true, mono: true, required: true }),
      B('dynamic', { label: 'Dynamic' }), DISABLED, COMMENT,
    ],
  },
  {
    path: 'interface/detect-internet', label: 'Detect Internet', category: 'interfaces', group: 'Lists & Detection', kind: 'singleton',
    icon: 'Globe2', availability: 'v7.16',
    fields: [E('detect-interface-list', ['none', 'all', 'dynamic'], { key: true }), E('wan-interface-list', ['none', 'all', 'dynamic'], { key: true }), D('internet-check-interval'), B('discover')],
  },
  { path: 'interface/traffic-monitor', label: 'Traffic Monitor', category: 'interfaces', group: 'Monitoring', kind: 'command', icon: 'Activity', availability: 'v7',
    description: 'Full-screen traffic monitor across one or more interfaces.',
    commands: [{ id: 'start', label: 'Start monitor', path: '', target: 'interface', params: [{ name: 'interface', label: 'Interface', type: 'string', required: true }, { name: 'duration', label: 'Duration', type: 'duration', default: '5s' }], response: 'json' }] },
  {
    path: 'interface/ethernet/switch/port', label: 'Switch Ports', category: 'interfaces', group: 'Hardware Switch', icon: 'Plug', demoRows: 5,
    fields: [S('name', { key: true, primary: true }), S('switch', { key: true }), B('default-vlan-id', { advanced: true }), S('vlan-mode', { key: true }), S('vlan-header', { key: true }), N('vlan-id', { key: true }), DISABLED, COMMENT],
  },
  { path: 'interface/ethernet/switch/vlan', label: 'Switch VLANs', category: 'interfaces', group: 'Hardware Switch', icon: 'Layers', demoRows: 0,
    fields: [S('name', { key: true }), S('switch', { key: true }), N('vlan-id', { key: true }), S('ports', { key: true }), S('svl', { advanced: true }), DISABLED, COMMENT] },
  { path: 'interface/ethernet/switch/rule', label: 'Switch Rules', category: 'interfaces', group: 'Hardware Switch', icon: 'Filter', demoRows: 0,
    fields: [S('switch', { key: true }), S('ports', { key: true }), S('mac-protocol', { key: true }), S('vlan-id', { key: true }), S('new-vlan-id', { key: true }), S('redirect-to', { advanced: true }), B('copy-to-cpu', { advanced: true }), DISABLED, COMMENT], ordered: true },
  { path: 'interface/ethernet/switch/host', label: 'Switch Hosts', category: 'interfaces', group: 'Hardware Switch', readOnly: true, icon: 'Table2', demoRows: 6,
    fields: [S('mac-address', { key: true, mono: true }), S('vid', { key: true }), S('ports', { key: true }), S('switch', { key: true }), B('dynamic', { label: 'Dynamic' })] },
  { path: 'interface/ethernet/switch/settings', label: 'Switch Settings', category: 'interfaces', group: 'Hardware Switch', kind: 'singleton', icon: 'Settings2',
    fields: [S('switch', { key: true }), B('mirror-egress', { advanced: true }), S('mirror-target'), B('mirror-ingress', { advanced: true }), S('sniffer'), B('sniffer-only', { advanced: true })] },
  { path: 'interface/ethernet/switch/l3-hw-offloading', label: 'L3 HW Offload', category: 'interfaces', group: 'Hardware Switch', kind: 'singleton', icon: 'Cpu',
    fields: [B('enabled', { key: true }), S('switch'), B('ipv4', { advanced: true }), B('ipv6', { advanced: true }), B('nat', { advanced: true }), B('fasttrack', { advanced: true })] },
];

/* ================================ IP ================================= */

const fwCommon: FieldDef[] = [
  N('index', { label: '#', width: 'xs' }),
  S('chain', { key: true, required: true, mono: true, primary: true }),
  E('action', ['accept', 'add-dst-to-address-list', 'add-src-to-address-list', 'drop', 'jump', 'log', 'passthrough', 'reject', 'return', 'tarpit'], { key: true, required: true, default: 'accept' }),
  C('src-address', { key: true }), C('dst-address', { key: true }),
  S('src-address-list', { key: true }), S('dst-address-list', { key: true }),
  S('src-port', { key: true, mono: true }), S('dst-port', { key: true, mono: true }),
  E('protocol', ['all', 'tcp', 'udp', 'icmp', 'igmp', 'gre', 'ipsec-ah', 'ipsec-esp', 'ospf', 'vrrp'], { key: true }),
  S('in-interface', { key: true }), S('out-interface', { key: true }),
  S('in-interface-list', { key: true }), S('out-interface-list', { key: true }),
  S('connection-state', { key: true }), S('connection-mark', { advanced: true }),
  S('packet-mark', { advanced: true }), S('routing-mark', { advanced: true }),
  S('jump-target', { key: true }), S('address-list', { key: true }), D('address-list-timeout', { advanced: true }),
  S('to-addresses', { key: true }), S('to-ports', { key: true }),
  S('log-prefix', { advanced: true }), B('log', { key: true }), S('new-connection-mark', { advanced: true }),
  BY('bytes', { key: true, label: 'Bytes' }), BY('packets', { key: true, label: 'Packets' }),
  DISABLED, DYN, INVALID, COMMENT,
];

export const ipEndpoints: EndpointDef[] = [
  {
    path: 'ip/address', label: 'Addresses', category: 'ip', group: 'Addressing', key: true, icon: 'AtSign', demoRows: 6, ordered: true,
    description: 'IP addresses assigned to interfaces.',
    fields: [
      C('address', { key: true, required: true, primary: true, placeholder: '192.168.88.1/24' }),
      S('network', { key: true, mono: true }), S('interface', { key: true, required: true, mono: true }),
      S('actual-interface', { key: true, mono: true }), I('broadcast'), DYN, INVALID, DISABLED, COMMENT,
    ],
    commands: [...ENABLE_DISABLE, ...ORDERED],
  },
  {
    path: 'ip/arp', label: 'ARP', category: 'ip', group: 'Addressing', icon: 'Table2', demoRows: 8,
    fields: [
      I('address', { key: true, required: true, primary: true }),
      { name: 'mac-address', type: 'mac', label: 'MAC', key: true, mono: true },
      S('interface', { key: true, required: true }), B('published', { advanced: true }), B('complete', { key: true }),
      DYN, INVALID, DISABLED, COMMENT,
    ],
    commands: ENABLE_DISABLE,
  },
  {
    path: 'ip/cloud', label: 'Cloud / DDNS', category: 'ip', group: 'Services', kind: 'singleton', icon: 'Cloud', key: true,
    fields: [
      B('ddns-enabled', { key: true, label: 'DDNS enabled' }),
      S('dns-name', { label: 'DNS name', key: true, mono: true }),
      I('public-address', { label: 'Public address', key: true }),
      S('status', { label: 'Status', key: true }),
      D('ddns-update-interval', { key: true }), D('update-time', { key: true, label: 'Last update' }),
      B('backup-allowed', { advanced: true }), B('ddns-ipv6', { advanced: true }),
      S('warning', { advanced: true, width: 'lg' }),
    ],
    commands: [
      { id: 'force-update', label: 'Force update', icon: 'RefreshCw', path: 'force-update', target: 'none', response: 'json' },
      { id: 'ddns-update', label: 'DDNS update', icon: 'Upload', path: 'ddns-update', target: 'none', response: 'json' },
    ],
  },
  {
    path: 'ip/dhcp-client', label: 'DHCP Clients', category: 'ip', group: 'DHCP', key: true, icon: 'Download', demoRows: 3,
    fields: [
      S('interface', { key: true, required: true, primary: true, mono: true }),
      S('address', { key: true, mono: true }), S('gateway', { key: true, mono: true }),
      S('status', { key: true }), D('expires-after', { key: true }),
      B('add-default-route', { key: true }), B('use-peer-dns', { key: true }), B('use-peer-ntp', { advanced: true }),
      S('primary-dns', { key: true, mono: true }), S('secondary-dns', { advanced: true, mono: true }),
      S('dhcp-options', { advanced: true }), I('client-id', { advanced: true }), D('lease-time', { advanced: true }),
      B('validate-server-duid', { advanced: true }), DISABLED, COMMENT,
    ],
    commands: [...ENABLE_DISABLE,
      { id: 'renew', label: 'Renew lease', icon: 'RefreshCw', path: 'renew', target: 'id' },
      { id: 'release', label: 'Release lease', icon: 'XCircle', path: 'release', target: 'id', danger: true }],
  },
  {
    path: 'ip/dhcp-server', label: 'DHCP Servers', category: 'ip', group: 'DHCP', key: true, icon: 'Server', demoRows: 3,
    fields: [
      NAME, S('interface', { key: true, required: true, mono: true }), S('address-pool', { key: true, mono: true }),
      D('lease-time', { key: true }), B('authoritative', { key: true }), B('add-arp', { advanced: true }),
      B('always-broadcast', { advanced: true }), B('use-radius', { advanced: true }), B('conflict-detection', { advanced: true }),
      S('bootp-support', { advanced: true }), D('delay-threshold', { advanced: true }), S('lease-script', { advanced: true }),
      S('address-lists', { advanced: true }), DYN, INVALID, DISABLED, COMMENT,
    ],
    commands: ENABLE_DISABLE,
  },
  {
    path: 'ip/dhcp-server/lease', label: 'DHCP Leases', category: 'ip', group: 'DHCP', key: true, icon: 'FileText', demoRows: 24,
    description: 'Active and static leases with make-static / remove actions.',
    fields: [
      I('address', { key: true, mono: true }), { name: 'mac-address', type: 'mac', label: 'MAC', key: true, mono: true, primary: true },
      S('host-name', { key: true }), S('server', { key: true }), S('status', { key: true, tone: 'success' }),
      D('expires-after', { key: true }), S('last-seen', { key: true }), B('dynamic', { key: true, label: 'Dynamic' }),
      B('blocked', { key: true, tone: 'danger' }), S('client-id', { advanced: true }), S('address-lists', { advanced: true }),
      S('dhcp-option', { advanced: true }), S('class-id', { advanced: true }), B('radius', { advanced: true }), DISABLED, COMMENT,
    ],
    commands: [
      ...ENABLE_DISABLE,
      { id: 'make-static', label: 'Make static', icon: 'Pin', path: 'make-static', target: 'id' },
      { id: 'check-status', label: 'Check status', icon: 'Activity', path: 'check-status', target: 'id', response: 'json' },
    ],
  },
  {
    path: 'ip/dhcp-server/network', label: 'DHCP Networks', category: 'ip', group: 'DHCP', icon: 'Globe', demoRows: 3,
    fields: [
      C('address', { key: true, required: true, primary: true }), I('gateway', { key: true }),
      I('netmask'), I('dns-server', { key: true, mono: true }), S('domain', { key: true }),
      B('dns-none', { advanced: true }), S('wins-server', { advanced: true }), S('ntp-server', { advanced: true, mono: true }),
      S('dhcp-option', { advanced: true }), S('dhcp-option-set', { advanced: true }), DYN, DISABLED, COMMENT,
    ],
  },
  {
    path: 'ip/dhcp-server/option', label: 'DHCP Options', category: 'ip', group: 'DHCP', icon: 'List', demoRows: 4,
    fields: [NAME, N('code', { key: true, required: true, primary: true }), S('value', { key: true, mono: true }), B('force', { key: true, advanced: true }), S('raw-value', { advanced: true })],
  },
  { path: 'ip/dhcp-server/option/sets', label: 'DHCP Option Sets', category: 'ip', group: 'DHCP', icon: 'ListTree', demoRows: 2,
    fields: [NAME, S('options', { key: true, mono: true })] },
  {
    path: 'ip/dhcp-relay', label: 'DHCP Relay', category: 'ip', group: 'DHCP', icon: 'Share2', demoRows: 0,
    fields: [NAME, S('interface', { key: true, required: true }), I('dhcp-server', { key: true, required: true }), I('local-address'),
      D('delay-threshold', { advanced: true }), B('add-relay-info', { advanced: true }), S('relay-info-remote-id', { advanced: true }), DISABLED, COMMENT],
    commands: ENABLE_DISABLE,
  },
  {
    path: 'ip/dns', label: 'DNS Settings', category: 'ip', group: 'DNS', kind: 'singleton', key: true, icon: 'Globe2',
    fields: [
      S('servers', { key: true, mono: true, label: 'Servers', placeholder: '1.1.1.1,8.8.8.8' }),
      B('allow-remote-requests', { key: true, label: 'Allow remote requests' }),
      N('cache-size', { key: true, unit: 'KiB' }), D('cache-max-ttl', { key: true }),
      S('doh-server', { advanced: true, mono: true, label: 'DoH server' }), B('use-doh-server', { advanced: true }),
      B('verify-doh-cert', { advanced: true }), N('cache-used', { advanced: true, unit: 'KiB' }),
      N('dynamic-server', { advanced: true }), B('mdns-repeat-ifaces', { advanced: true }), N('max-concurrent-queries', { advanced: true }),
      N('max-concurrent-tcp-sessions', { advanced: true }), D('max-udp-packet-size', { advanced: true }), S('query-server-timeout', { advanced: true }),
      S('query-total-timeout', { advanced: true }), S('address-list-extra-time', { advanced: true }),
    ],
  },
  {
    path: 'ip/dns/static', label: 'DNS Static', category: 'ip', group: 'DNS', key: true, icon: 'BookMarked', demoRows: 8, ordered: true,
    fields: [
      S('name', { key: true, primary: true, required: true, mono: true }),
      S('address', { key: true, mono: true }), S('cname', { advanced: true }), S('forward-to', { advanced: true, mono: true }),
      E('type', ['A', 'AAAA', 'CNAME', 'FWD', 'MX', 'NS', 'PTR', 'SRV', 'TXT', 'NXDOMAIN'], { key: true, default: 'A' }),
      D('ttl', { key: true }), S('address-list', { advanced: true }), B('match-subdomain', { advanced: true }),
      N('mx-preference', { advanced: true }), S('mx-exchange', { advanced: true }), S('text', { advanced: true }),
      N('srv-port', { advanced: true }), N('srv-priority', { advanced: true }), N('srv-weight', { advanced: true }),
      DYN, DISABLED, COMMENT,
    ],
  },
  {
    path: 'ip/dns/cache', label: 'DNS Cache', category: 'ip', group: 'DNS', readOnly: true, noCreate: true, noEdit: true, icon: 'Database', demoRows: 14,
    fields: [NAME, S('type', { key: true }), S('data', { key: true, mono: true }), D('ttl', { key: true }), S('address'), S('status', { key: true })],
    commands: [{ id: 'flush', label: 'Flush cache', icon: 'Trash2', path: 'flush', target: 'none', danger: true, confirm: 'Flush the entire DNS cache?' }],
  },
  { path: 'ip/pool', label: 'IP Pools', category: 'ip', group: 'Addressing', key: true, icon: 'Boxes', demoRows: 3,
    fields: [NAME, S('ranges', { key: true, mono: true, required: true, placeholder: '192.168.88.10-192.168.88.200' }), COMMENT] },
  {
    path: 'ip/service', label: 'IP Services', category: 'ip', group: 'Services', key: true, icon: 'Lock', demoRows: 8,
    description: 'Management services (api, ssh, winbox…) with port and source-address restrictions.',
    fields: [
      { name: 'name', type: 'string', key: true, primary: true, mono: true },
      N('port', { key: true }), S('address', { key: true, mono: true }),
      B('disabled', { key: true, tone: 'neutral', boolLabels: ['disabled', 'enabled'], label: 'Disabled' }),
      B('invalid', { tone: 'warning' }),
    ],
    commands: ENABLE_DISABLE,
  },
  {
    path: 'ip/settings', label: 'IP Settings', category: 'ip', group: 'Settings', kind: 'singleton', icon: 'Settings2',
    fields: [
      B('ip-forward', { key: true }), B('send-redirects', { key: true }), B('accept-redirects', { key: true }),
      B('accept-source-route', { key: true }), E('rp-filter', ['no', 'loose', 'strict'], { key: true }),
      B('secure-redirects', { key: true }), B('tcp-syncookies', { key: true }),
      N('icmp-rate-limit'), N('icmp-rate-mask'), B('allow-fast-path', { key: true }), N('max-neighbor-entries', { advanced: true }),
      B('ipv4-fast-path', { advanced: true }), N('arp-timeout', { advanced: true }), B('route-cache', { advanced: true }),
    ],
  },
  { path: 'ip/neighbor', label: 'Neighbors', category: 'ip', group: 'Discovery', readOnly: true, icon: 'Radar', demoRows: 6,
    description: 'MNDP/CDP/LLDP neighbor discovery results.',
    fields: [
      I('address', { key: true, mono: true, primary: true }), { name: 'mac-address', type: 'mac', label: 'MAC', key: true, mono: true },
      S('interface', { key: true }), S('identity', { key: true }), S('platform', { key: true }), S('version', { key: true }),
      S('board', { key: true }), S('discovered-by', { key: true }), D('age'),
    ],
  },
  { path: 'ip/neighbor/discovery-settings', label: 'Discovery Settings', category: 'ip', group: 'Discovery', kind: 'singleton', icon: 'Radar',
    fields: [S('discover-interface-list', { key: true }), S('protocol', { key: true }), D('protocol-raw'), S('mac-winbox'), S('mac-telnet')] },
  { path: 'ip/vrf', label: 'VRF', category: 'ip', group: 'Settings', icon: 'Split', availability: 'v7', demoRows: 2,
    fields: [NAME, S('interfaces', { key: true, mono: true }), S('table', { key: true }), DISABLED, COMMENT] },
  { path: 'ip/nexthop', label: 'Nexthops', category: 'ip', group: 'Settings', icon: 'Milestone', availability: 'v7', demoRows: 2,
    fields: [I('gateway', { key: true, mono: true, primary: true }), S('scope', { key: true }), S('target-scope', { key: true }),
      S('check-gateway', { key: true }), N('distance', { key: true }), B('on-link', { advanced: true }), I('pref-src', { advanced: true }), DISABLED, COMMENT] },
  { path: 'ip/route', label: 'Routes', category: 'ip', group: 'Routing', key: true, icon: 'Route', demoRows: 8, ordered: true,
    description: 'IPv4 routes — static, connected, dynamic and blackhole.',
    fields: [
      C('dst-address', { key: true, primary: true, mono: true, default: '0.0.0.0/0' }),
      I('gateway', { key: true, mono: true }), N('distance', { key: true }), S('scope', { key: true }),
      S('target-scope', { advanced: true }), S('check-gateway', { key: true }), B('active', { readonly: true, key: true, tone: 'success' } as unknown as Partial<FieldDef>),
      S('routing-table', { key: true }), B('blackhole', { advanced: true }), B('connect', { key: true, label: 'Connected' }),
      B('static', { key: true }), B('dynamic', { key: true }), B('suppress-hw-offload', { advanced: true }),
      I('pref-src', { advanced: true }), S('vrf-interface', { advanced: true }), DYN, DISABLED, COMMENT,
    ],
    commands: [...ENABLE_DISABLE, ...ORDERED,
      { id: 'check', label: 'Check gateway', icon: 'Activity', path: 'check', target: 'name', response: 'json' }],
  },
  { path: 'ip/smb', label: 'SMB Server', category: 'ip', group: 'Services', kind: 'singleton', icon: 'HardDrive',
    fields: [B('enabled', { key: true }), S('domain', { key: true }), S('comment', { key: true }), S('interfaces', { advanced: true }), E('smb-negotiation', ['auto', 'smb1', 'smb2'], { advanced: true })] },
  { path: 'ip/socks', label: 'SOCKS', category: 'ip', group: 'Services', kind: 'singleton', icon: 'Globe',
    fields: [B('enabled', { key: true }), N('port', { key: true }), N('connection-idle-timeout', { advanced: true }), N('max-connections', { advanced: true }), D('version')] },
  { path: 'ip/socks/users', label: 'SOCKS Users', category: 'ip', group: 'Services', icon: 'Users', demoRows: 0,
    fields: [NAME, F('password', 'password', { key: true }), DISABLED, COMMENT] },
  { path: 'ip/ssh', label: 'SSH Settings', category: 'ip', group: 'Services', kind: 'singleton', icon: 'Terminal', demoRows: 0,
    fields: [B('forwarding-enabled', { key: true })] },
  { path: 'ip/traffic-flow', label: 'Traffic Flow', category: 'ip', group: 'Monitoring', kind: 'singleton', icon: 'Waves',
    fields: [B('enabled', { key: true }), S('interfaces', { key: true }), B('cache-entries', { advanced: true }), D('active-flow-timeout', { advanced: true }), D('inactive-flow-timeout', { advanced: true })] },
  { path: 'ip/traffic-flow/target', label: 'Flow Targets', category: 'ip', group: 'Monitoring', icon: 'Target', demoRows: 0,
    fields: [C('dst-address', { key: true }), N('port', { key: true }), C('src-address'), N('v9-template-refresh', { advanced: true }), N('v9-template-timeout', { advanced: true }), DISABLED] },
  { path: 'ip/upnp', label: 'UPnP', category: 'ip', group: 'Services', kind: 'singleton', icon: 'Plug',
    fields: [B('enabled', { key: true }), B('allow-disable-external-interface', { key: true }), B('show-dummy-rule', { advanced: true })] },
  { path: 'ip/upnp/interfaces', label: 'UPnP Interfaces', category: 'ip', group: 'Services', icon: 'Plug', demoRows: 1,
    fields: [S('interface', { key: true }), E('type', ['external', 'internal'], { key: true }), B('forced-external-ip', { advanced: true }), DISABLED, COMMENT] },
  { path: 'ip/packing', label: 'IP Packing', category: 'ip', group: 'Settings', kind: 'singleton', icon: 'Package', availability: 'optional',
    fields: [B('enabled', { key: true }), D('aggregate-time'), N('aggregate-size'), D('timeout')] },
  { path: 'ip/kid-control', label: 'Kid Control', category: 'ip', group: 'Access Control', icon: 'Baby', demoRows: 2,
    fields: [NAME, DISABLED, COMMENT, B('dynamic', { label: 'Dynamic' })],
    commands: ENABLE_DISABLE,
  },
  { path: 'ip/kid-control/device', label: 'Kid Control Devices', category: 'ip', group: 'Access Control', icon: 'Baby', demoRows: 4,
    fields: [
      { name: 'mac-address', type: 'mac', label: 'MAC', key: true, primary: true, mono: true, required: true },
      NAME, D('rate-limit', { key: true }), S('blocking', { key: true }), S('day-rates', { advanced: true }),
      B('disabled', { key: true, tone: 'neutral', boolLabels: ['paused', 'active'] }), COMMENT,
    ],
  },
];

/* =============================== IPv6 ================================ */

export const ipv6Endpoints: EndpointDef[] = [
  { path: 'ipv6/address', label: 'IPv6 Addresses', category: 'ipv6', group: 'Addressing', key: true, icon: 'AtSign', demoRows: 4,
    fields: [
      C('address', { key: true, primary: true, required: true, mono: true }),
      S('interface', { key: true, required: true, mono: true }), S('actual-interface', { key: true, mono: true }),
      B('advertise', { key: true }), B('eui-64', { key: true }), B('no-dad', { advanced: true }), B('deprecated', { advanced: true }),
      DYN, INVALID, DISABLED, COMMENT,
    ], commands: ENABLE_DISABLE },
  { path: 'ipv6/route', label: 'IPv6 Routes', category: 'ipv6', group: 'Routing', key: true, icon: 'Route', demoRows: 5,
    fields: [
      C('dst-address', { key: true, primary: true, mono: true }), S('gateway', { key: true, mono: true }),
      N('distance', { key: true }), S('scope', { key: true }), S('routing-table', { key: true }), S('check-gateway', { advanced: true }),
      B('active', { key: true }), B('dynamic', { key: true }), B('static', { key: true }), B('connect', { key: true }), B('blackhole', { advanced: true }), DISABLED, COMMENT,
    ], commands: [...ENABLE_DISABLE, ...ORDERED] },
  { path: 'ipv6/dhcp-client', label: 'DHCPv6 Client', category: 'ipv6', group: 'DHCP', icon: 'Download', demoRows: 1,
    fields: [S('interface', { key: true, primary: true }), S('status', { key: true }), S('address', { key: true, mono: true }), D('expires-after', { key: true }),
      B('add-default-route', { key: true }), B('use-peer-dns', { key: true }), B('request', { advanced: true }), S('pool-name', { advanced: true }),
      S('prefix-hint', { advanced: true }), S('dhcp-options', { advanced: true }), D('rapid-commit'), DISABLED, COMMENT],
    commands: [...ENABLE_DISABLE, { id: 'renew', label: 'Renew', icon: 'RefreshCw', path: 'renew', target: 'id' }, { id: 'release', label: 'Release', icon: 'XCircle', path: 'release', target: 'id', danger: true }] },
  { path: 'ipv6/dhcp-server', label: 'DHCPv6 Server', category: 'ipv6', group: 'DHCP', icon: 'Server', demoRows: 1,
    fields: [NAME, S('interface', { key: true }), S('address-pool', { key: true }), D('lease-time', { key: true }), S('prefix-pool', { advanced: true }), B('rapid-commit', { advanced: true }), D('route-distance'), S('dns-server', { advanced: true }), DISABLED, COMMENT],
    commands: ENABLE_DISABLE },
  { path: 'ipv6/pool', label: 'IPv6 Pools', category: 'ipv6', group: 'Addressing', icon: 'Boxes', demoRows: 1,
    fields: [NAME, S('prefix', { key: true, mono: true }), S('prefix-length', { key: true }), S('from-pool', { advanced: true }), DISABLED, COMMENT] },
  { path: 'ipv6/nd', label: 'ND Settings', category: 'ipv6', group: 'Neighbor Discovery', kind: 'singleton', icon: 'Radar',
    fields: [D('ra-interval', { key: true }), B('ra-delay'), D('ra-lifetime'), B('ra-preference'), N('ra-advrouter-mode', { advanced: true }), N('hop-limit', { advanced: true }), B('managed-address-configuration', { advanced: true }), B('other-configuration', { advanced: true }), N('reachable-time', { advanced: true }), N('retransmit-interval', { advanced: true }), S('mtu', { advanced: true })] },
  { path: 'ipv6/nd/prefix', label: 'ND Prefixes', category: 'ipv6', group: 'Neighbor Discovery', icon: 'Layers', demoRows: 2,
    fields: [S('prefix', { key: true, primary: true, mono: true, required: true }), S('interface', { key: true }), B('on-link', { key: true }), B('autonomous', { key: true }),
      D('valid-lifetime', { key: true }), D('preferred-lifetime', { key: true }), B('deprecated', { advanced: true }), DISABLED, COMMENT] },
  { path: 'ipv6/neighbor', label: 'IPv6 Neighbors', category: 'ipv6', group: 'Neighbor Discovery', readOnly: true, icon: 'Table2', demoRows: 5,
    fields: [S('address', { key: true, mono: true, primary: true }), { name: 'mac-address', type: 'mac', key: true, mono: true }, S('interface', { key: true }), S('status', { key: true }), B('router', { key: true }), B('dynamic', { key: true }), B('incomplete', { advanced: true })] },
  { path: 'ipv6/settings', label: 'IPv6 Settings', category: 'ipv6', group: 'Settings', kind: 'singleton', icon: 'Settings2',
    fields: [B('forwarding', { key: true }), B('accept-redirects', { key: true }), B('accept-router-advertisements', { key: true }), E('accept-router-advertisements', ['no', 'yes', 'yes-if-forwarding-disabled'], { key: true }), B('disable-ipv6', { advanced: true }), B('softwire-enabled', { advanced: true }), N('max-neighbor-entries', { advanced: true })] },
  { path: 'ipv6/firewall/filter', label: 'IPv6 Filter', category: 'ipv6', group: 'Firewall', icon: 'ShieldCheck', demoRows: 6, ordered: true,
    fields: fwCommon.map((f) => ({ ...f })), commands: [...ENABLE_DISABLE, ...ORDERED,
      { id: 'reset-counters', label: 'Reset counters', icon: 'RotateCcw', path: 'reset-counters', target: 'numbers' }] },
  { path: 'ipv6/firewall/nat', label: 'IPv6 NAT', category: 'ipv6', group: 'Firewall', icon: 'ArrowLeftRight', demoRows: 2, ordered: true,
    fields: fwCommon.map((f) => ({ ...f })), commands: [...ENABLE_DISABLE, ...ORDERED] },
  { path: 'ipv6/firewall/mangle', label: 'IPv6 Mangle', category: 'ipv6', group: 'Firewall', icon: 'Wand2', demoRows: 3, ordered: true,
    fields: fwCommon.map((f) => ({ ...f })), commands: [...ENABLE_DISABLE, ...ORDERED] },
  { path: 'ipv6/firewall/raw', label: 'IPv6 RAW', category: 'ipv6', group: 'Firewall', icon: 'Zap', demoRows: 3, ordered: true,
    fields: fwCommon.map((f) => ({ ...f })), commands: [...ENABLE_DISABLE, ...ORDERED] },
  { path: 'ipv6/firewall/address-list', label: 'IPv6 Address Lists', category: 'ipv6', group: 'Firewall', icon: 'ListChecks', demoRows: 5,
    fields: [S('list', { key: true, required: true }), C('address', { key: true, primary: true, mono: true, required: true }), D('timeout', { key: true }), D('creation-time'), B('dynamic', { key: true }), DISABLED, COMMENT] },
];

/* ============================= FIREWALL ============================== */

const fwCommands = [...ENABLE_DISABLE, ...ORDERED,
  { id: 'reset-counters', label: 'Reset counters', icon: 'RotateCcw', path: 'reset-counters', target: 'numbers' }];

export const firewallEndpoints: EndpointDef[] = [
  { path: 'ip/firewall/filter', label: 'Filter Rules', category: 'firewall', group: 'IPv4', key: true, icon: 'ShieldCheck', demoRows: 14, ordered: true,
    description: 'The main packet filter. Live byte/packet counters refresh automatically.',
    fields: fwCommon, live: ['bytes', 'packets'], commands: fwCommands },
  { path: 'ip/firewall/nat', label: 'NAT', category: 'firewall', group: 'IPv4', key: true, icon: 'ArrowLeftRight', demoRows: 8, ordered: true,
    fields: [
      N('index', { label: '#', width: 'xs' }), S('chain', { key: true, required: true, mono: true, primary: true }),
      E('action', ['accept', 'add-dst-to-address-list', 'add-src-to-address-list', 'dst-nat', 'jump', 'log', 'masquerade', 'netmap', 'passthrough', 'redirect', 'return', 'same', 'src-nat'], { key: true, required: true, default: 'masquerade' }),
      C('src-address', { key: true }), C('dst-address', { key: true }), S('src-address-list', { key: true }), S('dst-address-list', { key: true }),
      S('src-port', { key: true, mono: true }), S('dst-port', { key: true, mono: true }), E('protocol', ['all', 'tcp', 'udp', 'icmp'], { key: true }),
      S('in-interface', { key: true }), S('out-interface', { key: true }), S('in-interface-list', { key: true }), S('out-interface-list', { key: true }),
      S('to-addresses', { key: true }), S('to-ports', { key: true }), S('connection-mark', { advanced: true }), S('jump-target', { key: true }),
      BY('bytes', { key: true, label: 'Bytes' }), BY('packets', { key: true, label: 'Packets' }),
      B('log', { key: true }), S('log-prefix', { advanced: true }), DISABLED, DYN, INVALID, COMMENT,
    ], live: ['bytes', 'packets'], commands: fwCommands },
  { path: 'ip/firewall/mangle', label: 'Mangle', category: 'firewall', group: 'IPv4', key: true, icon: 'Wand2', demoRows: 10, ordered: true,
    fields: [
      N('index', { label: '#', width: 'xs' }), S('chain', { key: true, required: true, mono: true, primary: true }),
      E('action', ['accept', 'add-dst-to-address-list', 'add-src-to-address-list', 'change-dscp', 'change-mss', 'change-ttl', 'clear-df', 'jump', 'log', 'mark-connection', 'mark-packet', 'mark-routing', 'passthrough', 'return', 'route', 'set-priority', 'strip-ipv4-options'], { key: true, required: true, default: 'mark-packet' }),
      C('src-address', { key: true }), C('dst-address', { key: true }), S('src-address-list', { key: true }), S('dst-address-list', { key: true }),
      S('src-port', { key: true }), S('dst-port', { key: true }), E('protocol', ['all', 'tcp', 'udp', 'icmp'], { key: true }),
      S('in-interface', { key: true }), S('out-interface', { key: true }), S('new-packet-mark', { key: true }), S('new-connection-mark', { key: true }),
      S('new-routing-mark', { key: true }), N('new-dscp', { advanced: true }), S('new-mss', { advanced: true }), S('new-ttl', { advanced: true }),
      S('passthrough', { advanced: true }), S('route-dst', { advanced: true }), BY('bytes', { key: true }), BY('packets', { key: true }),
      B('log', { advanced: true }), DISABLED, DYN, INVALID, COMMENT,
    ], live: ['bytes', 'packets'], commands: fwCommands },
  { path: 'ip/firewall/raw', label: 'RAW', category: 'firewall', group: 'IPv4', key: true, icon: 'Zap', demoRows: 8, ordered: true,
    fields: [
      N('index', { label: '#', width: 'xs' }), S('chain', { key: true, required: true, mono: true, primary: true }),
      E('action', ['accept', 'add-dst-to-address-list', 'add-src-to-address-list', 'drop', 'jump', 'log', 'notrack', 'passthrough', 'return'], { key: true, required: true, default: 'notrack' }),
      C('src-address', { key: true }), C('dst-address', { key: true }), S('src-address-list', { key: true }), S('dst-address-list', { key: true }),
      S('src-port', { key: true }), S('dst-port', { key: true }), E('protocol', ['all', 'tcp', 'udp', 'icmp'], { key: true }),
      S('in-interface', { key: true }), S('out-interface', { key: true }), S('jump-target', { advanced: true }),
      BY('bytes', { key: true }), BY('packets', { key: true }), B('log', { advanced: true }), DISABLED, DYN, INVALID, COMMENT,
    ], live: ['bytes', 'packets'], commands: fwCommands },
  { path: 'ip/firewall/address-list', label: 'Address Lists', category: 'firewall', group: 'Objects', key: true, icon: 'ListChecks', demoRows: 12,
    description: 'Named address groups usable in firewall rules, DNS and routing.',
    fields: [
      S('list', { key: true, required: true, primary: true }),
      C('address', { key: true, mono: true, required: true }),
      D('timeout', { key: true }), D('creation-time', { key: true }),
      B('dynamic', { key: true, label: 'Dynamic' }), DISABLED, COMMENT,
    ],
  },
  { path: 'ip/firewall/connection', label: 'Connections', category: 'firewall', group: 'Tracking', readOnly: true, noCreate: true, noEdit: true, icon: 'Activity', demoRows: 30,
    description: 'Live conntrack table with per-flow byte counters.',
    fields: [
      E('protocol', ['tcp', 'udp', 'icmp', 'other'], { key: true }),
      S('src-address', { key: true, mono: true, primary: true }), S('dst-address', { key: true, mono: true }),
      S('src-port', { key: true, mono: true, width: 'xs' }), S('dst-port', { key: true, mono: true, width: 'xs' }),
      S('tcp-state', { key: true }), S('state', { key: true }), D('timeout', { key: true }),
      BY('orig-bytes', { key: true, label: 'Orig' }), BY('repl-bytes', { key: true, label: 'Reply' }),
      S('connection-mark', { advanced: true }), S('connection-type', { advanced: true }), B('fasttrack', { key: true, label: 'Fasttrack' }),
      S('srcnat-address', { advanced: true }), S('dstnat-address', { advanced: true }),
    ],
    live: ['orig-bytes', 'repl-bytes'],
    commands: [{ id: 'dump', label: 'Dump to file', icon: 'Download', path: 'dump', target: 'none', body: { file: 'connection-dump.txt' }, response: 'json' }] },
  { path: 'ip/firewall/connection/tracking', label: 'Conntrack Settings', category: 'firewall', group: 'Tracking', kind: 'singleton', icon: 'Settings2',
    fields: [
      B('enabled', { key: true }), B('loose-tcp-tracking', { key: true }), N('max-entries', { key: true }),
      D('tcp-syn-sent-timeout', { key: true }), D('tcp-established-timeout', { key: true }), D('tcp-fin-wait-timeout', { advanced: true }),
      D('tcp-close-wait-timeout', { advanced: true }), D('tcp-last-ack-timeout', { advanced: true }), D('tcp-time-wait-timeout', { advanced: true }),
      D('tcp-close-timeout', { advanced: true }), D('tcp-max-retrans-timeout', { advanced: true }), D('tcp-unacked-timeout', { advanced: true }),
      D('udp-timeout', { key: true }), D('udp-stream-timeout', { advanced: true }), D('icmp-timeout', { advanced: true }), D('generic-timeout', { advanced: true }),
    ],
    commands: [{ id: 'tracking', label: 'Tracking stats', icon: 'Activity', path: 'tracking', target: 'none', body: { once: '' }, response: 'json' }] },
  { path: 'ip/firewall/service-port', label: 'Service Ports', category: 'firewall', group: 'Objects', readOnly: true, icon: 'Plug', demoRows: 10,
    fields: [S('name', { key: true, primary: true }), S('port', { key: true }), S('sip-direct-media', { advanced: true }), S('sip-timeout', { advanced: true })] },
  { path: 'ip/firewall/layer7-protocol', label: 'Layer7 Protocols', category: 'firewall', group: 'Objects', icon: 'Wand2', availability: 'optional', demoRows: 3,
    description: 'Layer-7 matchers (removed in RouterOS 7.16 — kept for older devices).',
    fields: [NAME, S('regexp', { key: true, width: 'lg', mono: true, required: true }), COMMENT] },
  { path: 'ip/firewall/helper', label: 'Helpers', category: 'firewall', group: 'Objects', icon: 'LifeBuoy', demoRows: 3,
    fields: [S('name', { key: true }), B('enabled', { key: true }), N('port'), S('comment'), B('dynamic', { advanced: true })] },
  { path: 'ip/firewall/address-list/index', label: 'Address List Index', category: 'firewall', group: 'Objects', readOnly: true, hidden: true, icon: 'Table2', demoRows: 0, fields: [S('name', { key: true })] },
];

/* ============================== ROUTING ============================== */

export const routingEndpoints: EndpointDef[] = [
  { path: 'routing/table', label: 'Routing Tables', category: 'routing', group: 'Tables & Rules', key: true, icon: 'Table2', availability: 'v7', demoRows: 3,
    fields: [NAME, S('fib', { key: true }), DISABLED, COMMENT] },
  { path: 'routing/rule', label: 'Policy Rules', category: 'routing', group: 'Tables & Rules', key: true, icon: 'Filter', availability: 'v7', demoRows: 3, ordered: true,
    fields: [C('src-address', { key: true, primary: true }), C('dst-address', { key: true }), S('action', { key: true, type: 'enum', values: ['lookup', 'drop', 'unreachable'], required: true }),
      S('table', { key: true }), S('vrf', { advanced: true }), C('min-prefix', { advanced: true }), B('disabled', { key: true, tone: 'neutral', boolLabels: ['disabled', 'enabled'] }), COMMENT],
    commands: [...ENABLE_DISABLE, ...ORDERED] },
  { path: 'routing/settings', label: 'Routing Settings', category: 'routing', group: 'Tables & Rules', kind: 'singleton', icon: 'Settings2', availability: 'v7',
    fields: [D('check-gateway-ping-timeout', { key: true }), S('single-process', { advanced: true }), N('max-sessions', { advanced: true })] },
  { path: 'routing/ospf/instance', label: 'OSPF Instances', category: 'routing', group: 'OSPF', key: true, icon: 'Network', availability: 'v7', demoRows: 1,
    fields: [NAME, S('router-id', { key: true, mono: true }), S('vrf', { key: true }), S('distribute-default', { key: true }),
      S('redistribute-connected', { advanced: true }), S('redistribute-static', { advanced: true }), S('redistribute-bgp', { advanced: true }),
      D('spf-interval', { advanced: true }), S('originate-default', { advanced: true }), DISABLED, COMMENT] },
  { path: 'routing/ospf/area', label: 'OSPF Areas', category: 'routing', group: 'OSPF', key: true, icon: 'Boxes', availability: 'v7', demoRows: 2,
    fields: [NAME, S('instance', { key: true, required: true }), S('area-id', { key: true, mono: true }), E('type', ['default', 'stub', 'nssa'], { key: true }), DISABLED, COMMENT] },
  { path: 'routing/ospf/interface-template', label: 'OSPF Interfaces', category: 'routing', group: 'OSPF', key: true, icon: 'Cable', availability: 'v7', demoRows: 3,
    fields: [S('areas', { key: true, required: true }), S('interfaces', { key: true, primary: true, required: true }), S('network-type', { key: true }),
      N('cost', { key: true }), N('priority', { key: true }), D('hello-interval', { key: true }), D('dead-interval', { key: true }),
      B('passive', { key: true }), N('instance-id', { advanced: true }), B('disabled', { key: true, tone: 'neutral', boolLabels: ['disabled', 'enabled'] }), COMMENT] },
  { path: 'routing/ospf/neighbor', label: 'OSPF Neighbors', category: 'routing', group: 'OSPF', readOnly: true, icon: 'Radar', availability: 'v7.16', demoRows: 2,
    fields: [S('router-id', { key: true, mono: true, primary: true }), S('address', { key: true, mono: true }), S('interface', { key: true }), S('state', { key: true }), S('area', { key: true })] },
  { path: 'routing/bgp/connection', label: 'BGP Connections', category: 'routing', group: 'BGP', key: true, icon: 'Globe', availability: 'v7', demoRows: 2,
    fields: [NAME, S('remote.address', { key: true, mono: true, primary: true, required: true }), N('remote.as', { key: true, required: true }),
      N('remote.port', { key: true }), N('local.role', { advanced: true }), S('template', { key: true }), S('local.address', { advanced: true, mono: true }),
      B('multihop', { key: true }), N('multihop', { advanced: true }), B('connect', { advanced: true }), B('listen', { advanced: true }),
      S('routing-table', { key: true }), D('hold-time', { advanced: true }), D('keepalive-time', { advanced: true }), S('nexthop-choice', { advanced: true }),
      DISABLED, COMMENT] },
  { path: 'routing/bgp/template', label: 'BGP Templates', category: 'routing', group: 'BGP', key: true, icon: 'FileCode2', availability: 'v7', demoRows: 1,
    fields: [NAME, N('as', { key: true, required: true }), S('router-id', { key: true, mono: true }), S('local.role', { key: true }),
      S('routing-table', { key: true }), D('hold-time', { key: true }), D('keepalive-time', { advanced: true }), S('nexthop-choice', { advanced: true }),
      S('address-families', { advanced: true }), S('output.network', { advanced: true }), S('output.redistribute', { advanced: true }), DISABLED, COMMENT] },
  { path: 'routing/bgp/session', label: 'BGP Sessions', category: 'routing', group: 'BGP', readOnly: true, icon: 'Activity', availability: 'v7', demoRows: 2,
    description: 'Live BGP peer state, uptime and prefix counters.',
    fields: [NAME, S('remote.address', { key: true, mono: true, primary: true }), N('remote.as', { key: true }), S('state', { key: true }),
      D('uptime', { key: true }), N('prefix-count', { key: true }), S('local.role', { key: true }), S('remote.id', { key: true, mono: true }),
      S('last-error', { key: true }), S('established', { key: true })] },
  { path: 'routing/bgp/advertisement', label: 'BGP Advertisements', category: 'routing', group: 'BGP', readOnly: true, icon: 'Megaphone', availability: 'v7.16', demoRows: 0,
    fields: [S('prefix', { key: true, mono: true }), S('nexthop', { key: true, mono: true }), N('as-path', { key: true }), S('local-pref', { key: true }), S('communities', { key: true }), S('origin', { key: true })] },
  { path: 'routing/rip', label: 'RIP', category: 'routing', group: 'Other Protocols', icon: 'RefreshCw', availability: 'v7', demoRows: 1,
    fields: [NAME, S('interfaces', { key: true }), S('distribute-default', { key: true }), S('redistribute-connected', { advanced: true }),
      S('redistribute-static', { advanced: true }), N('metric', { key: true }), S('routes', { advanced: true }), DISABLED, COMMENT] },
  { path: 'routing/ripng', label: 'RIPng', category: 'routing', group: 'Other Protocols', icon: 'RefreshCw', availability: 'v7', demoRows: 0,
    fields: [NAME, S('interfaces', { key: true }), S('distribute-default', { key: true }), N('metric', { key: true }), DISABLED, COMMENT] },
  { path: 'routing/bfd/configuration', label: 'BFD', category: 'routing', group: 'Other Protocols', icon: 'HeartPulse', availability: 'v7', demoRows: 1,
    fields: [NAME, S('interfaces', { key: true }), D('min-tx', { key: true }), D('min-rx', { key: true }), N('multiplier', { key: true }), D('transmit-interval', { advanced: true }), D('receive-interval', { advanced: true }), DISABLED, COMMENT] },
  { path: 'routing/filter/rule', label: 'Filter Rules', category: 'routing', group: 'Filters', icon: 'Filter', availability: 'v7', demoRows: 4,
    fields: [S('chain', { key: true, required: true }), S('rule', { key: true, width: 'lg', mono: true, required: true }), B('disabled', { key: true, tone: 'neutral', boolLabels: ['disabled', 'enabled'] }), COMMENT] },
  { path: 'routing/filter/select-rule', label: 'Select Rules', category: 'routing', group: 'Filters', icon: 'Filter', availability: 'v7', demoRows: 2,
    fields: [S('chain', { key: true }), S('do', { key: true }), S('rule', { key: true, mono: true }), DISABLED, COMMENT] },
  { path: 'routing/filter/num-list', label: 'Number Lists', category: 'routing', group: 'Filters', icon: 'List', availability: 'v7', demoRows: 2,
    fields: [NAME, S('ranges', { key: true, mono: true }), DISABLED, COMMENT] },
  { path: 'routing/igmp-proxy', label: 'IGMP Proxy', category: 'routing', group: 'Multicast', icon: 'Radio', availability: 'v7', demoRows: 0,
    fields: [NAME, S('interface', { key: true }), S('source-address', { advanced: true }), B('quick-leave', { advanced: true }), DISABLED, COMMENT] },
  { path: 'routing/igmp-proxy/interface', label: 'IGMP Interfaces', category: 'routing', group: 'Multicast', icon: 'Radio', availability: 'v7', demoRows: 0,
    fields: [S('interface', { key: true }), E('upstream', ['yes', 'no'], { key: true }), S('alternative-subnets', { advanced: true }), S('threshold', { advanced: true })] },
  { path: 'routing/igmp-proxy/mfc', label: 'Multicast Forwarding', category: 'routing', group: 'Multicast', readOnly: true, icon: 'Radio', availability: 'v7', demoRows: 0,
    fields: [S('source', { key: true }), S('group', { key: true }), S('upstream-interface', { key: true }), S('downstream-interfaces', { key: true }), S('bytes', { key: true })] },
  { path: 'routing/pimsm', label: 'PIM Settings', category: 'routing', group: 'Multicast', kind: 'singleton', icon: 'Radio', availability: 'optional',
    fields: [B('enabled', { key: true }), S('rp-address', { key: true }), S('bsm-forward-back', { advanced: true })] },
  { path: 'routing/pimsm/interface', label: 'PIM Interfaces', category: 'routing', group: 'Multicast', icon: 'Radio', availability: 'optional', demoRows: 0,
    fields: [NAME, S('interface', { key: true }), N('priority', { key: true }), D('hello-period', { advanced: true }), B('join-prune', { advanced: true }), DISABLED, COMMENT] },
];

/* =============================== QUEUES ============================== */

const queueCommon: FieldDef[] = [
  S('max-limit', { key: true, mono: true, placeholder: '10M', help: 'Maximum rate, e.g. 10M / 10M for upload/download.' }),
  S('limit-at', { key: true, mono: true, advanced: true, placeholder: '2M' }),
  S('burst-limit', { mono: true, advanced: true }), S('burst-threshold', { mono: true, advanced: true }), D('burst-time', { advanced: true }),
  E('priority', ['1', '2', '3', '4', '5', '6', '7', '8'], { key: true, default: '8' }),
  S('queue', { advanced: true, placeholder: 'default-small' }), D('time', { advanced: true }),
  S('rate', { key: true, mono: true, label: 'Rate', help: 'Live rate (read-only)' }),
  S('packet-rate', { key: true, label: 'PPS' }), BY('bytes', { key: true }),
  BY('queued-bytes', { advanced: true }), BY('dropped', { advanced: true }), BY('total-bytes', { advanced: true }),
];

export const queueEndpoints: EndpointDef[] = [
  { path: 'queue/simple', label: 'Simple Queues', category: 'queues', group: 'Queues', key: true, icon: 'Gauge', demoRows: 8, ordered: true,
    description: 'Bandwidth shaping per target with live rate monitoring.',
    fields: [
      NAME, S('target', { key: true, mono: true, required: true, primary: true, placeholder: '192.168.88.0/24' }),
      S('dst', { key: true, mono: true }), ...queueCommon,
      B('disabled', { key: true, tone: 'neutral', boolLabels: ['disabled', 'enabled'] }), COMMENT,
    ],
    live: ['rate', 'packet-rate', 'bytes', 'queued-bytes', 'dropped'],
    commands: [...ENABLE_DISABLE, ...ORDERED,
      { id: 'reset-counters', label: 'Reset counters', icon: 'RotateCcw', path: 'reset-counters', target: 'numbers' }] },
  { path: 'queue/tree', label: 'Queue Tree', category: 'queues', group: 'Queues', key: true, icon: 'GitBranch', demoRows: 5, ordered: true,
    fields: [
      NAME, S('parent', { key: true, required: true, mono: true, primary: true }), S('packet-mark', { key: true }),
      ...queueCommon, B('disabled', { key: true, tone: 'neutral', boolLabels: ['disabled', 'enabled'] }), COMMENT,
    ],
    live: ['rate', 'packet-rate', 'bytes', 'queued-bytes', 'dropped'],
    commands: [...ENABLE_DISABLE, ...ORDERED,
      { id: 'reset-counters', label: 'Reset counters', icon: 'RotateCcw', path: 'reset-counters', target: 'numbers' }] },
  { path: 'queue/type', label: 'Queue Types', category: 'queues', group: 'Configuration', key: true, icon: 'Sliders', demoRows: 5,
    fields: [NAME, E('kind', ['bfifo', 'cake', 'fq-codel', 'pcq', 'pfifo', 'red', 'sfq'], { key: true, required: true }),
      S('pcq-rate', { key: true, mono: true }), S('pcq-classifier', { key: true }), S('pcq-burst-rate', { advanced: true }),
      S('pcq-burst-threshold', { advanced: true }), D('pcq-burst-time', { advanced: true }), N('pcq-limit', { advanced: true }),
      N('pcq-total-limit', { advanced: true }), S('cake-bandwidth', { advanced: true }), S('cake-diffserv', { advanced: true }),
      S('cake-flowmode', { advanced: true }), S('cake-nat', { advanced: true }), S('cake-overhead', { advanced: true }),
      B('fq-codel-ce-threshold', { advanced: true }), B('fq-codel-interval', { advanced: true }), N('red-limit', { advanced: true }), S('sfq-perturb', { advanced: true })] },
  { path: 'queue/interface', label: 'Interface Queues', category: 'queues', group: 'Configuration', icon: 'Cable', availability: 'optional', demoRows: 0,
    fields: [S('interface', { key: true, primary: true }), S('queue', { key: true }), D('burst-time', { advanced: true }), DISABLED, COMMENT] },
];

/* ================================ MPLS =============================== */

export const mplsEndpoints: EndpointDef[] = [
  { path: 'mpls/ldp', label: 'LDP', category: 'mpls', group: 'LDP', kind: 'singleton', icon: 'Share2', availability: 'v7',
    fields: [B('enabled', { key: true }), I('lsr-id', { key: true, mono: true }), S('transport-addresses', { key: true }),
      S('path-vector-limit', { advanced: true }), B('use-explicit-null', { advanced: true }), B('afi-ip', { advanced: true }), B('afi-vpn', { advanced: true })] },
  { path: 'mpls/ldp/neighbor', label: 'LDP Neighbors', category: 'mpls', group: 'LDP', readOnly: true, icon: 'Radar', availability: 'v7', demoRows: 0,
    fields: [S('transport', { key: true, mono: true }), S('peer', { key: true, mono: true }), S('state', { key: true }), D('up-time', { key: true }), S('local-transport', { key: true })] },
  { path: 'mpls/interface', label: 'Interfaces', category: 'mpls', group: 'Configuration', icon: 'Cable', availability: 'v7', demoRows: 2,
    fields: [S('interface', { key: true, primary: true }), B('disabled', { key: true, tone: 'neutral', boolLabels: ['disabled', 'enabled'] }), COMMENT] },
  { path: 'mpls/local-mapping', label: 'Local Mapping', category: 'mpls', group: 'Configuration', icon: 'ListTree', availability: 'v7', demoRows: 2,
    fields: [C('dst-address', { key: true, mono: true, primary: true }), N('label', { key: true }), DISABLED, COMMENT] },
  { path: 'mpls/remote-mapping', label: 'Remote Mapping', category: 'mpls', group: 'Configuration', readOnly: true, icon: 'ListTree', availability: 'v7', demoRows: 3,
    fields: [C('dst-address', { key: true, mono: true }), N('label', { key: true }), S('nexthop', { key: true, mono: true }), S('path', { key: true })] },
  { path: 'mpls/forwarding-table', label: 'Forwarding Table', category: 'mpls', group: 'Configuration', readOnly: true, icon: 'Table2', availability: 'v7', demoRows: 3,
    fields: [S('label', { key: true, primary: true }), N('in-label', { key: true }), S('out-label', { key: true }), S('nexthop', { key: true, mono: true }), S('interface', { key: true }), BY('bytes', { key: true })] },
];
