import { B, BY, C, COMMENT, D, DISABLED, DYN, E, ENABLE_DISABLE, F, I, INVALID, N, NAME, ORDERED, S, T, type EndpointDef } from '../types';

/** Wireless, PPP, VPN, hotspot, RADIUS and User Manager menus. */

const AUTH_TYPES = ['wpa-psk', 'wpa2-psk', 'wpa3-psk', 'wpa-eap', 'wpa2-eap', 'wpa3-eap', 'wpa-psk-sha2', 'owe'];
const CIPHERS = ['aes-ccm', 'tkip', 'ccmp', 'ccmp-256', 'gcmp', 'gcmp-256'];
const ZT = { key: true };

export const wirelessEndpoints: EndpointDef[] = [
  /* ---------------- WiFi (RouterOS 7.13+, wifiwave2) ---------------- */
  {
    path: 'interface/wifi', label: 'WiFi Interfaces', category: 'wireless', group: 'WiFi', key: true, icon: 'Wifi', availability: 'v7.13', demoRows: 3,
    description: 'Modern WiFi interfaces (wifiwave2) with configuration, security and datapath profiles.',
    fields: [
      NAME,
      S('ssid', { key: true, primary: true }),
      S('configuration', { key: true, mono: true }), S('security', { key: true, mono: true }), S('datapath', { key: true, mono: true }),
      S('master-interface', { key: true }), S('channel', { advanced: true }), S('country', { advanced: true }),
      B('running', { key: true }), S('state', { key: true }), D('uptime', { key: true }),
      DISABLED, COMMENT,
    ],
    commands: [
      ...ENABLE_DISABLE,
      { id: 'monitor', label: 'Monitor', icon: 'Activity', path: 'monitor', target: 'name', body: { once: '' }, response: 'json' },
      { id: 'scan', label: 'Scan networks', icon: 'Radar', path: 'scan', target: 'name', body: { duration: '5' }, response: 'json' },
      { id: 'frequency-monitor', label: 'Frequency monitor', icon: 'Waves', path: 'frequency-monitor', target: 'name', body: { duration: '5' }, response: 'json' },
      { id: 'reset-counters', label: 'Reset counters', icon: 'RotateCcw', path: 'reset-counters', target: 'numbers' },
    ],
  },
  {
    path: 'interface/wifi/configuration', label: 'WiFi Configurations', category: 'wireless', group: 'WiFi', key: true, icon: 'Sliders', availability: 'v7.13', demoRows: 2,
    fields: [
      NAME, S('ssid', { key: true, primary: true }), S('country', { key: true }), E('mode', ['ap', 'station', 'station-bridge', 'sniffer'], { key: true }),
      S('band', { key: true }), S('channel', { key: true }), S('width', { key: true }), S('frequency', { key: true }),
      B('hide-ssid', { key: true }), E('installation', ['indoor', 'outdoor'], { advanced: true }), N('antenna-gain', { advanced: true }),
      N('tx-power', { advanced: true }), D('dtim-period', { advanced: true }), B('multicast-enhancer', { advanced: true }),
      D('country', { advanced: true }), B('qos-classifier', { advanced: true }), S('station-roaming', { advanced: true }), DISABLED, COMMENT,
    ],
    commands: ENABLE_DISABLE,
  },
  {
    path: 'interface/wifi/security', label: 'WiFi Security', category: 'wireless', group: 'WiFi', key: true, icon: 'Lock', availability: 'v7.13', demoRows: 2,
    fields: [
      NAME, E('authentication-types', AUTH_TYPES, { key: true }),
      F('passphrase', 'password', { key: true, help: 'WPA pre-shared key (8-63 characters).' }),
      E('encryption', CIPHERS, { advanced: true }), B('wps', { advanced: true }), D('group-key-update', { advanced: true }),
      B('ft', { advanced: true }), B('ft-over-ds', { advanced: true }), E('management-protection', ['allowed', 'required', 'disabled'], { advanced: true }),
      S('eap-methods', { advanced: true }), B('wps-push-button', { advanced: true, immutable: true }), DISABLED, COMMENT,
    ],
  },
  {
    path: 'interface/wifi/datapath', label: 'WiFi Datapaths', category: 'wireless', group: 'WiFi', key: true, icon: 'Share2', availability: 'v7.13', demoRows: 2,
    fields: [NAME, S('bridge', { key: true }), N('vlan-id', { key: true }), N('bridge-cost', { advanced: true }), N('bridge-horizon', { advanced: true }),
      B('client-isolation', { key: true }), S('interface-list', { advanced: true }), S('traffic-processing', { advanced: true }), DISABLED, COMMENT],
  },
  {
    path: 'interface/wifi/access-list', label: 'WiFi Access List', category: 'wireless', group: 'WiFi', icon: 'ListChecks', availability: 'v7.13', demoRows: 3, ordered: true,
    fields: [
      E('action', ['accept', 'reject', 'query-radius'], { key: true, required: true, default: 'accept' }),
      { name: 'mac-address', type: 'mac', label: 'MAC', key: true, mono: true, primary: true },
      S('interface', { key: true }), S('signal-range', { key: true }), S('address', { key: true, mono: true }),
      B('allow-signal-out-of-range', { advanced: true }), S('authentication', { advanced: true }), D('time'), DISABLED, COMMENT,
    ],
    commands: [...ENABLE_DISABLE, ...ORDERED],
  },
  {
    path: 'interface/wifi/registration-table', label: 'WiFi Clients', category: 'wireless', group: 'WiFi', readOnly: true, noCreate: true, noEdit: true, icon: 'Users', availability: 'v7.13', demoRows: 12,
    description: 'Connected wireless clients with signal, rates and traffic counters.',
    fields: [
      { name: 'mac-address', type: 'mac', label: 'MAC', key: true, mono: true, primary: true },
      S('interface', { key: true }), S('ssid', { key: true }), D('uptime', { key: true }),
      S('signal', { key: true, tone: 'info' }), S('tx-rate', { key: true }), S('rx-rate', { key: true }),
      BY('bytes', { key: true, label: 'Bytes' }), S('packets', { key: true }), S('tx-packets', { advanced: true }),
      S('rx-signal', { advanced: true }), S('authorized', { key: true }), S('eap-identity', { advanced: true }), S('last-ip', { key: true, mono: true }),
    ],
    live: ['bytes', 'packets'],
    commands: [{ id: 'remove', label: 'Disconnect', icon: 'UserMinus', path: 'remove', target: 'numbers', danger: true, confirm: 'Disconnect this client?' }],
  },
  {
    path: 'interface/wifi/channel', label: 'WiFi Channels', category: 'wireless', group: 'WiFi', readOnly: true, icon: 'Waves', availability: 'v7.13', demoRows: 4,
    fields: [NAME, S('band', { key: true }), S('frequency', { key: true }), S('width', { key: true }), S('tx-power', { key: true }), S('regulatory-domain', { advanced: true })] },
  {
    path: 'interface/wifi/radio', label: 'WiFi Radios', category: 'wireless', group: 'WiFi', readOnly: true, icon: 'Radio', availability: 'v7.13', demoRows: 2,
    fields: [NAME, { name: 'mac-address', type: 'mac', label: 'MAC', key: true, mono: true }, S('band', { key: true }), S('channel', { key: true }),
      S('current-channel', { key: true }), S('width', { key: true }), N('registered-clients', { key: true }), S('interfaces', { key: true })] },
  {
    path: 'interface/wifi/provisioning', label: 'WiFi Provisioning', category: 'wireless', group: 'WiFi', icon: 'Wrench', availability: 'v7.13', demoRows: 1, ordered: true,
    fields: [E('action', ['create-disabled', 'create-enabled', 'create-dynamic-enabled'], { key: true, required: true }),
      S('identity-regexp', { key: true }), S('address-ranges', { key: true }), S('master-configuration', { key: true, required: true }),
      S('slave-configurations', { key: true }), { name: 'radio-mac', type: 'mac', label: 'Radio MAC', key: true, mono: true },
      S('name-format', { advanced: true }), B('common-name-regexp', { advanced: true }), DISABLED, COMMENT],
    commands: [...ENABLE_DISABLE, ...ORDERED] },

  /* ---------------- Legacy wireless (pre-7.13) ---------------- */
  {
    path: 'interface/wireless', label: 'Wireless (legacy)', category: 'wireless', group: 'Legacy', icon: 'Wifi', availability: 'optional', demoRows: 0, hidden: true,
    description: 'Legacy wireless package (pre-7.13 devices without wifiwave2).',
    fields: [NAME, S('ssid', { key: true, primary: true }), E('mode', ['ap-bridge', 'bridge', 'station', 'station-bridge', 'station-wds', 'ap'], { key: true }),
      S('band', { key: true }), S('frequency', { key: true }), S('channel-width', { key: true }), S('security-profile', { key: true }),
      S('country', { key: true }), N('tx-power', { advanced: true }), S('wireless-protocol', { advanced: true }), B('running', { key: true }), DISABLED, COMMENT],
    commands: [...ENABLE_DISABLE,
      { id: 'monitor', label: 'Monitor', icon: 'Activity', path: 'monitor', target: 'name', body: { once: '' }, response: 'json' },
      { id: 'scan', label: 'Scan', icon: 'Radar', path: 'scan', target: 'name', body: { duration: '5' }, response: 'json' }],
  },
  { path: 'interface/wireless/registration-table', label: 'Wireless Clients (legacy)', category: 'wireless', group: 'Legacy', readOnly: true, icon: 'Users', availability: 'optional', hidden: true, demoRows: 0,
    fields: [{ name: 'mac-address', type: 'mac', label: 'MAC', key: true, mono: true }, S('interface', { key: true }), D('uptime', { key: true }), S('signal-strength', { key: true }), S('tx-rate', { key: true }), S('rx-rate', { key: true }), BY('bytes', { key: true })] },
  { path: 'interface/wireless/security-profiles', label: 'Security Profiles (legacy)', category: 'wireless', group: 'Legacy', icon: 'Lock', availability: 'optional', hidden: true, demoRows: 0,
    fields: [NAME, E('authentication-types', ['wpa-psk', 'wpa2-psk', 'wpa-eap', 'wpa2-eap'], { key: true }), S('mode', { key: true }), S('unicast-ciphers', { key: true }), S('group-ciphers', { key: true }), F('wpa-pre-shared-key', 'password'), F('wpa2-pre-shared-key', 'password')] },
  { path: 'interface/wireless/access-list', label: 'Access List (legacy)', category: 'wireless', group: 'Legacy', icon: 'ListChecks', availability: 'optional', hidden: true, demoRows: 0,
    fields: [{ name: 'mac-address', type: 'mac', label: 'MAC', key: true, mono: true }, S('interface', { key: true }), S('authentication', { key: true }), S('signal-range', { key: true }), DISABLED, COMMENT] },
  { path: 'interface/wireless/connect-list', label: 'Connect List (legacy)', category: 'wireless', group: 'Legacy', icon: 'ListPlus', availability: 'optional', hidden: true, demoRows: 0,
    fields: [S('interface', { key: true }), S('connect', { key: true }), S('ssid', { key: true }), S('security-profile', { key: true }), DISABLED, COMMENT] },
];

export const pppEndpoints: EndpointDef[] = [
  {
    path: 'interface/pppoe-client', label: 'PPPoE Clients', category: 'ppp', group: 'Clients', key: true, icon: 'Download', demoRows: 2,
    fields: [
      NAME, S('interface', { key: true, required: true, mono: true }), S('user', { key: true, required: true }), F('password', 'password', { key: true }),
      S('service', { advanced: true }), S('ac-name', { advanced: true }), S('profile', { key: true }),
      B('add-default-route', { key: true }), N('default-route-distance', { advanced: true }), B('use-peer-dns', { key: true }),
      B('dial-on-demand', { advanced: true }), D('keepalive-timeout', { advanced: true }), N('max-mtu', { advanced: true }), N('max-mru', { advanced: true }),
      S('uptime', { key: true }), S('status', { key: true }), I('local-address', {}, ), I('remote-address', {}), DISABLED, COMMENT,
    ],
    commands: [...ENABLE_DISABLE, { id: 'unset', label: 'Unset', icon: 'Eraser', path: 'unset', target: 'id', params: [{ name: 'value-name', label: 'Property', type: 'string', placeholder: 'ipv6' }] },
      { id: 'monitor', label: 'Monitor', icon: 'Activity', path: 'monitor', target: 'name', body: { once: '' }, response: 'json' }],
  },
  {
    path: 'ppp/profile', label: 'PPP Profiles', category: 'ppp', group: 'Profiles', key: true, icon: 'FileCode2', demoRows: 3,
    fields: [
      NAME, I('local-address'), I('remote-address', { key: true }), S('dns-server', { key: true, mono: true }),
      S('rate-limit', { key: true, mono: true, label: 'Rate limit', placeholder: '10M/10M' }),
      D('session-timeout', { key: true }), D('idle-timeout', { key: true }), B('only-one', { key: true }),
      B('change-tcp-mss', { advanced: true }), B('use-compression', { advanced: true }), B('use-encryption', { advanced: true }),
      B('use-ipv6', { advanced: true }), B('use-mpls', { advanced: true }), B('use-upnp', { advanced: true }), B('use-radius', { advanced: true }),
      N('address-list', { advanced: true }), S('on-up', { advanced: true }), S('on-down', { advanced: true }),
      S('bridge', { advanced: true }), N('bridge-port-pvid', { advanced: true }), N('bridge-horizon', { advanced: true }),
      DISABLED, COMMENT,
    ],
  },
  {
    path: 'ppp/secret', label: 'PPP Secrets', category: 'ppp', group: 'Secrets', key: true, icon: 'KeyRound', demoRows: 16,
    description: 'PPPoE/L2TP/PPTP accounts. Add a secret when a client dials in; they appear under Active sessions.',
    fields: [
      NAME, F('password', 'password', { key: true }), S('service', { key: true, default: 'pppoe' }),
      S('profile', { key: true }), I('remote-address', { key: true }), I('local-address', { advanced: true }),
      S('routes', { advanced: true, mono: true }), S('limit-bytes-in', { advanced: true }), S('limit-bytes-out', { advanced: true }),
      D('last-logged-out', { advanced: true }), S('caller-id', { advanced: true }), DISABLED, COMMENT,
    ],
  },
  {
    path: 'ppp/active', label: 'Active Sessions', category: 'ppp', group: 'Secrets', readOnly: true, noCreate: true, noEdit: true, icon: 'Activity', key: true, demoRows: 10,
    fields: [
      NAME, S('service', { key: true }), S('caller-id', { key: true, mono: true }), I('address', { key: true }),
      D('uptime', { key: true }), S('encoding', { key: true }), S('session-id', { key: true }),
      BY('limit-bytes-in', { advanced: true }), BY('limit-bytes-out', { advanced: true }), B('radius', { advanced: true }),
    ],
    commands: [
      { id: 'remove', label: 'Disconnect', icon: 'UserMinus', path: 'remove', target: 'numbers', danger: true, confirm: 'Disconnect this session?' },
      { id: 'monitor', label: 'Monitor', icon: 'Activity', path: 'monitor', target: 'name', body: { once: '' }, response: 'json' },
    ],
  },
  {
    path: 'ppp/aaa', label: 'PPP AAA', category: 'ppp', group: 'Settings', kind: 'singleton', icon: 'ShieldCheck',
    fields: [B('use-radius', { key: true }), B('accounting', { key: true }), D('interim-update'), B('use-circuit-id-in-nas-port-id', { advanced: true }), B('use-realm-for-roaming', { advanced: true })],
    commands: [{ id: 'enable', label: 'Enable AAA', icon: 'Power', path: 'enable', target: 'none' }, { id: 'disable', label: 'Disable AAA', icon: 'PowerOff', path: 'disable', target: 'none' }],
  },
  { path: 'ppp/l2tp-secret', label: 'L2TP Secrets', category: 'ppp', group: 'Secrets', icon: 'KeyRound', demoRows: 2, hidden: true,
    fields: [NAME, F('password', 'password', { key: true }), S('service', { key: true }), S('profile', { key: true }), I('remote-address', { key: true }), DISABLED, COMMENT] },
];

export const vpnEndpoints: EndpointDef[] = [
  /* ---------------- WireGuard ---------------- */
  {
    path: 'interface/wireguard', label: 'WireGuard', category: 'vpn', group: 'WireGuard', key: true, icon: 'Waypoints', availability: 'v7', demoRows: 2,
    description: 'WireGuard server/client interfaces. Private keys are generated on the router with `/interface/wireguard/add`.',
    fields: [
      NAME, N('listen-port', { key: true }), F('private-key', 'password', { key: true }),
      S('public-key', { key: true, mono: true, immutable: true, help: 'Derived from the private key.' }),
      N('mtu', { key: true }), DISABLED, COMMENT,
    ],
    commands: ENABLE_DISABLE,
  },
  {
    path: 'interface/wireguard/peers', label: 'WireGuard Peers', category: 'vpn', group: 'WireGuard', key: true, icon: 'Users', availability: 'v7', demoRows: 6,
    fields: [
      S('interface', { key: true, required: true, mono: true }),
      S('public-key', { key: true, mono: true, primary: true, required: true }),
      S('endpoint-address', { key: true, mono: true }), N('endpoint-port', { key: true }),
      C('allowed-address', { key: true, mono: true, required: true }), F('preshared-key', 'password', { advanced: true }),
      D('persistent-keepalive', { key: true }), S('current-endpoint-address', { key: true, mono: true }),
      D('last-handshake', { key: true }), BY('rx', { key: true, label: 'RX', live: true } as any), BY('tx', { key: true, label: 'TX', live: true } as any),
      B('responder', { advanced: true }), DISABLED, COMMENT,
    ],
    live: ['rx', 'tx'],
    commands: ENABLE_DISABLE,
  },
  /* ---------------- OpenVPN ---------------- */
  {
    path: 'interface/ovpn-client', label: 'OpenVPN Clients', category: 'vpn', group: 'OpenVPN', key: true, icon: 'Lock', availability: 'v7', demoRows: 1,
    fields: [
      NAME, S('connect-to', { key: true, mono: true, required: true }), N('port', { key: true, default: 1194 }),
      S('user', { key: true }), F('password', 'password', { key: true }), S('profile', { key: true }),
      S('certificate', { key: true, mono: true }), E('auth', ['sha1', 'sha256', 'sha512', 'md5'], { key: true }),
      E('cipher', ['aes-128-cbc', 'aes-192-cbc', 'aes-256-cbc', 'aes-128-gcm', 'aes-256-gcm', 'blowfish-128-cbc'], { key: true }),
      B('add-default-route', { key: true }), D('keepalive-timeout', { advanced: true }), B('verify-server-certificate', { advanced: true }),
      B('tls-version', { advanced: true }), N('max-mtu', { advanced: true }), S('status', { key: true }), DISABLED, COMMENT,
    ],
    commands: ENABLE_DISABLE,
  },
  {
    path: 'interface/ovpn-server', label: 'OpenVPN Servers', category: 'vpn', group: 'OpenVPN', key: true, icon: 'Server', availability: 'v7', demoRows: 1,
    fields: [
      NAME, S('user', { key: true }), F('password', 'password', { key: true }), S('profile', { key: true }),
      S('certificate', { key: true, mono: true }), E('auth', ['sha1', 'sha256', 'sha512'], { key: true }),
      E('cipher', ['aes-128-cbc', 'aes-256-cbc', 'aes-128-gcm', 'aes-256-gcm'], { key: true }),
      E('mode', ['ip', 'tap'], { key: true }), S('netmask', { key: true }), N('max-mtu', { advanced: true }),
      D('keepalive-timeout', { advanced: true }), N('port', { advanced: true }), S('on-up', { advanced: true }), S('on-down', { advanced: true }),
      S('status', { key: true }), S('local-address', { key: true, mono: true }), S('remote-address', { advanced: true }), DISABLED, COMMENT,
    ],
    commands: ENABLE_DISABLE,
  },
  {
    path: 'interface/ovpn-server/server', label: 'OpenVPN Server Settings', category: 'vpn', group: 'OpenVPN', kind: 'singleton', icon: 'Settings2', availability: 'v7', hidden: true,
    fields: [B('enabled', { key: true }), S('certificate', { key: true }), E('auth', ['sha1', 'sha256', 'sha512'], { key: true }), E('cipher', ['aes-256-cbc', 'aes-256-gcm'], { key: true }), E('mode', ['ip', 'tap'], { key: true }), B('require-client-certificate', { key: true }), D('keepalive-timeout')],
  },
  /* ---------------- SSTP ---------------- */
  {
    path: 'interface/sstp-client', label: 'SSTP Clients', category: 'vpn', group: 'SSTP', key: true, icon: 'Lock', availability: 'v7', demoRows: 1,
    fields: [
      NAME, S('connect-to', { key: true, mono: true, required: true }), N('port', { key: true }), S('user', { key: true }), F('password', 'password', { key: true }),
      S('profile', { key: true }), B('add-default-route', { key: true }), B('verify-server-certificate', { key: true }),
      S('certificate', { advanced: true }), D('keepalive-timeout', { advanced: true }), B('pfs', { advanced: true }), S('tls-version', { advanced: true }),
      S('status', { key: true }), DISABLED, COMMENT,
    ],
    commands: ENABLE_DISABLE,
  },
  {
    path: 'interface/sstp-server', label: 'SSTP Servers', category: 'vpn', group: 'SSTP', key: true, icon: 'Server', availability: 'v7', demoRows: 1,
    fields: [NAME, S('user', { key: true }), F('password', 'password', { key: true }), S('profile', { key: true }), S('certificate', { key: true }),
      B('verify-client-certificate', { advanced: true }), N('port'), S('status', { key: true }), DISABLED, COMMENT],
    commands: ENABLE_DISABLE,
  },
  /* ---------------- IPsec ---------------- */
  {
    path: 'ip/ipsec/peer', label: 'IPsec Peers', category: 'vpn', group: 'IPsec', key: true, icon: 'Users', demoRows: 2,
    fields: [NAME, I('address', { key: true, mono: true, required: true }), N('port', { key: true }), S('profile', { key: true }),
      E('exchange-mode', ['main', 'aggressive', 'ike2'], { key: true }), B('send-initial-contact', { key: true }),
      S('name', { key: true }), S('local-address', { advanced: true }), B('passive', { advanced: true }), DISABLED, COMMENT],
    commands: ENABLE_DISABLE,
  },
  {
    path: 'ip/ipsec/profile', label: 'IPsec Profiles', category: 'vpn', group: 'IPsec', key: true, icon: 'FileCode2', demoRows: 3,
    fields: [NAME, S('hash-algorithm', { key: true }), S('enc-algorithm', { key: true }), S('dh-group', { key: true }), D('lifetime', { key: true }),
      S('proposal-check', { key: true }), B('nat-traversal', { key: true }), B('generate-policy', { advanced: true }), S('exchange-mode', { advanced: true }), DISABLED, COMMENT],
    commands: ENABLE_DISABLE,
  },
  {
    path: 'ip/ipsec/proposal', label: 'IPsec Proposals', category: 'vpn', group: 'IPsec', key: true, icon: 'FileCode2', demoRows: 3,
    fields: [NAME, S('auth-algorithms', { key: true }), S('enc-algorithms', { key: true }), D('lifetime', { key: true }), S('pfs-group', { key: true }), DISABLED, COMMENT],
    commands: ENABLE_DISABLE,
  },
  {
    path: 'ip/ipsec/identity', label: 'IPsec Identities', category: 'vpn', group: 'IPsec', key: true, icon: 'Fingerprint', demoRows: 3,
    fields: [S('peer', { key: true, primary: true }), S('my-id', { key: true, mono: true }), S('remote-id', { key: true, mono: true }),
      E('auth-method', ['pre-shared-key', 'rsa-signature', 'digital-signature', 'eap', 'eap-radius'], { key: true, required: true }),
      F('secret', 'password', { key: true }), S('certificate', { advanced: true }), S('generate-policy', { key: true }),
      S('match-by', { advanced: true }), S('mode-config', { advanced: true }), S('policy-template-group', { advanced: true }),
      DYN, DISABLED, COMMENT],
  },
  {
    path: 'ip/ipsec/policy', label: 'IPsec Policies', category: 'vpn', group: 'IPsec', key: true, icon: 'ShieldCheck', demoRows: 4, ordered: true,
    fields: [C('src-address', { key: true, mono: true, primary: true, required: true }), C('dst-address', { key: true, mono: true, required: true }),
      S('src-port', { key: true }), S('dst-port', { key: true }), E('protocol', ['all', 'tcp', 'udp', 'icmp'], { key: true }),
      E('action', ['encrypt', 'discard', 'none'], { key: true, required: true }), S('level', { key: true }), S('ipsec-protocols', { key: true }),
      S('proposal', { key: true }), N('tunnel', { key: true, type: 'boolean' } as any), S('peer', { key: true }), S('template', { advanced: true }),
      I('sa-src-address', { advanced: true }), I('sa-dst-address', { advanced: true }), BY('ph2-count', { key: true }),
      DYN, DISABLED, COMMENT],
    commands: [...ENABLE_DISABLE, ...ORDERED],
  },
  {
    path: 'ip/ipsec/mode-config', label: 'IPsec Mode Config', category: 'vpn', group: 'IPsec', icon: 'Sliders', demoRows: 1,
    fields: [NAME, S('address-pool', { key: true }), N('address-prefix-length', { key: true }), S('split-include', { advanced: true }),
      B('system-dns', { key: true }), B('send-dns', { advanced: true }), S('dns-server', { advanced: true }), DISABLED, COMMENT],
  },
  {
    path: 'ip/ipsec/active-peers', label: 'IPsec Active Peers', category: 'vpn', group: 'IPsec', readOnly: true, icon: 'Activity', demoRows: 3,
    fields: [I('remote-address', { key: true, mono: true, primary: true }), S('state', { key: true }), D('uptime', { key: true }), N('ph2-total', { key: true }),
      BY('rx', { key: true, label: 'RX' }), BY('tx', { key: true, label: 'TX' }), I('local-address'), B('responder', { key: true }), S('side', { key: true })],
    live: ['rx', 'tx'],
    commands: [{ id: 'kill', label: 'Kill connection', icon: 'XCircle', path: 'kill', target: 'numbers', danger: true, confirm: 'Terminate this IPsec peer?' }] },
  {
    path: 'ip/ipsec/installed-sa', label: 'IPsec SAs', category: 'vpn', group: 'IPsec', readOnly: true, icon: 'Table2', demoRows: 5,
    fields: [C('src-address', { key: true }), C('dst-address', { key: true }), S('state', { key: true }), S('spi', { key: true, mono: true }),
      S('auth-algorithm', { key: true }), S('enc-algorithm', { key: true }), BY('bytes', { key: true }), S('ph2-state', { key: true }), D('uptime', { key: true })],
    live: ['bytes'],
    commands: [{ id: 'flush', label: 'Flush SAs', icon: 'Trash2', path: 'flush', target: 'none', danger: true, confirm: 'Flush all installed IPsec SAs?' }] },
  { path: 'ip/ipsec/settings', label: 'IPsec Settings', category: 'vpn', group: 'IPsec', kind: 'singleton', icon: 'Settings2', availability: 'v7', hidden: true,
    fields: [B('src-address', { key: true }), B('logging', { advanced: true }), N('max-peers', { advanced: true })] },
  /* ---------------- ZeroTier ---------------- */
  {
    path: 'zerotier', label: 'ZeroTier', category: 'vpn', group: 'ZeroTier', key: true, icon: 'Boxes', availability: 'v7.13', demoRows: 1,
    description: 'Joined ZeroTier networks (name is the 16-character network ID).',
    fields: [NAME, S('status', { key: true }), S('identity', { key: true, mono: true }), S('interface', { key: true }), B('disabled', { key: true, tone: 'neutral', boolLabels: ['disabled', 'enabled'] }), COMMENT],
    commands: ENABLE_DISABLE,
  },
  { path: 'zerotier/peer', label: 'ZeroTier Peers', category: 'vpn', group: 'ZeroTier', readOnly: true, icon: 'Users', availability: 'v7.13', demoRows: 2, hidden: true,
    fields: [S('id', { key: true, mono: true }), S('address', { key: true }), S('path', { key: true }), S('latency', { key: true }), S('version', { key: true }), S('role', { key: true })] },
];

export const hotspotEndpoints: EndpointDef[] = [
  { path: 'ip/hotspot', label: 'Hotspot Servers', category: 'hotspot', group: 'Servers', key: true, icon: 'Flame', demoRows: 2,
    fields: [NAME, S('interface', { key: true, required: true }), S('address-pool', { key: true }), S('profile', { key: true }),
      D('idle-timeout', { key: true }), D('keepalive-timeout', { advanced: true }), N('addresses-per-mac', { advanced: true }),
      D('hops', { advanced: true }), I('address', { key: true }), DISABLED, INVALID, COMMENT],
    commands: [...ENABLE_DISABLE, { id: 'reset-html', label: 'Reset HTML', icon: 'FileText', path: 'reset-html', target: 'none', danger: true, confirm: 'Restore the default hotspot login page?' }] },
  { path: 'ip/hotspot/profile', label: 'Hotspot Profiles', category: 'hotspot', group: 'Servers', key: true, icon: 'FileCode2', demoRows: 2,
    fields: [NAME, I('hotspot-address', { key: true }), S('dns-name', { key: true, mono: true }), S('html-directory', { key: true }),
      S('login-by', { key: true }), B('use-radius', { key: true }), S('rate-limit', { key: true, mono: true }),
      D('http-cookie-lifetime', { advanced: true }), B('split-user-domain', { advanced: true }), S('smtp-server', { advanced: true }),
      B('transparent-proxy', { advanced: true }), B('open-status-page', { advanced: true }), D('session-timeout', { advanced: true }),
      D('idle-timeout', { advanced: true }), S('nas-port-type', { advanced: true }), B('radius-accounting', { advanced: true }),
      S('radius-interim-update', { advanced: true }), S('radius-location-id', { advanced: true }), S('radius-location-name', { advanced: true }),
      S('ssl-certificate', { advanced: true }), S('http-proxy', { advanced: true }), B('login-timeout', { advanced: true })],
    commands: ENABLE_DISABLE },
  { path: 'ip/hotspot/user', label: 'Hotspot Users', category: 'hotspot', group: 'Users', key: true, icon: 'Users', demoRows: 12,
    description: 'Voucher/login accounts. Usage limits can be combined (time, bytes, uptime).',
    fields: [
      NAME, F('password', 'password', { key: true }), S('profile', { key: true }),
      D('limit-uptime', { key: true }), S('limit-bytes-in', { key: true }), S('limit-bytes-out', { key: true }),
      S('limit-bytes-total', { advanced: true }), { name: 'mac-address', type: 'mac', label: 'MAC', key: true, mono: true },
      S('server', { key: true }), I('address', { advanced: true }), S('routes', { advanced: true }), S('email', { advanced: true }),
      D('uptime', { key: true }), BY('bytes-in', { key: true }), BY('bytes-out', { key: true }),
      DISABLED, COMMENT,
    ],
    live: ['uptime', 'bytes-in', 'bytes-out'],
    commands: ENABLE_DISABLE },
  { path: 'ip/hotspot/user/profile', label: 'Hotspot User Profiles', category: 'hotspot', group: 'Users', key: true, icon: 'FileCode2', demoRows: 3,
    fields: [NAME, N('shared-users', { key: true }), S('rate-limit', { key: true, mono: true }), D('session-timeout', { key: true }),
      D('idle-timeout', { key: true }), D('keepalive-timeout', { advanced: true }), B('add-mac-cookie', { key: true }),
      D('mac-cookie-timeout', { advanced: true }), S('on-login', { advanced: true }), S('on-logout', { advanced: true }),
      S('address-list', { advanced: true }), S('status-autorefresh', { advanced: true }), B('transparent-proxy', { advanced: true }), B('open-status-page', { advanced: true })] },
  { path: 'ip/hotspot/active', label: 'Active Sessions', category: 'hotspot', group: 'Sessions', readOnly: true, noCreate: true, noEdit: true, icon: 'Activity', key: true, demoRows: 18,
    fields: [S('server', { key: true }), S('user', { key: true, primary: true }), I('address', { key: true }),
      { name: 'mac-address', type: 'mac', label: 'MAC', key: true, mono: true }, S('login-by', { key: true }), D('uptime', { key: true }),
      BY('bytes-in', { key: true }), BY('bytes-out', { key: true }), S('idle-time', { key: true }), D('session-time-left', { key: true }), B('radius', { advanced: true })],
    live: ['bytes-in', 'bytes-out'],
    commands: [{ id: 'remove', label: 'Disconnect', icon: 'UserMinus', path: 'remove', target: 'numbers', danger: true, confirm: 'Disconnect this hotspot user?' }] },
  { path: 'ip/hotspot/host', label: 'Hotspot Hosts', category: 'hotspot', group: 'Sessions', readOnly: true, icon: 'MonitorSmartphone', demoRows: 14,
    fields: [{ name: 'mac-address', type: 'mac', label: 'MAC', key: true, mono: true, primary: true }, I('address', { key: true }),
      I('to-address', { key: true }), S('server', { key: true }), D('uptime', { key: true }), D('idle-time', { key: true }),
      B('dynamic', { key: true }), B('blocked', { key: true, tone: 'danger' }), B('authorized', { key: true })],
    commands: [
      { id: 'make-binding', label: 'Make binding', icon: 'Pin', path: 'make-binding', target: 'numbers' },
      { id: 'remove', label: 'Remove', icon: 'Trash2', path: 'remove', target: 'numbers', danger: true, confirm: 'Remove this host entry?' },
    ] },
  { path: 'ip/hotspot/ip-binding', label: 'IP Bindings', category: 'hotspot', group: 'Sessions', key: true, icon: 'ListPlus', demoRows: 4,
    fields: [I('address', { key: true, mono: true, primary: true }), { name: 'mac-address', type: 'mac', label: 'MAC', key: true, mono: true },
      E('type', ['bypassed', 'blocked', 'regular'], { key: true, required: true }), S('server', { key: true }), I('to-address', { advanced: true }),
      B('dynamic', { key: true }), DISABLED, COMMENT] },
  { path: 'ip/hotspot/cookie', label: 'Cookies', category: 'hotspot', group: 'Sessions', readOnly: true, icon: 'Cookie', demoRows: 6, hidden: true,
    fields: [S('user', { key: true }), { name: 'mac-address', type: 'mac', label: 'MAC', key: true, mono: true }, S('domain', { key: true }), S('expires-in', { key: true })],
    commands: [{ id: 'remove', label: 'Remove', icon: 'Trash2', path: 'remove', target: 'numbers', danger: true }] },
  { path: 'ip/hotspot/walled-garden', label: 'Walled Garden', category: 'hotspot', group: 'Walled Garden', key: true, icon: 'Fence', demoRows: 6,
    fields: [E('action', ['allow', 'deny'], { key: true, required: true }), S('server', { key: true }), C('src-address', { key: true }),
      C('dst-address', { key: true }), S('dst-host', { key: true, mono: true, primary: true }), S('dst-port', { key: true }), S('path', { advanced: true }),
      S('method', { advanced: true }), S('protocol', { key: true }), S('dst-address-list', { advanced: true }), DISABLED, COMMENT],
    commands: ENABLE_DISABLE },
  { path: 'ip/hotspot/walled-garden/ip', label: 'Walled Garden IP', category: 'hotspot', group: 'Walled Garden', icon: 'Fence', demoRows: 2,
    fields: [E('action', ['allow', 'deny'], { key: true, required: true }), S('server', { key: true }), C('src-address', { key: true }),
      C('dst-address', { key: true, primary: true }), E('protocol', ['tcp', 'udp', 'icmp', 'all'], { key: true }), S('dst-port', { key: true }), DISABLED, COMMENT] },
];

export const radiusEndpoints: EndpointDef[] = [
  { path: 'radius', label: 'RADIUS Clients', category: 'radius', group: 'Clients', key: true, icon: 'Server', demoRows: 2,
    description: 'RADIUS servers used for hotspot, PPP, login, wireless and DHCP authentication.',
    fields: [E('service', ['hotspot', 'ppp', 'login', 'wireless', 'capsman', 'dhcp', 'dot1x'], { key: true, required: true }),
      I('address', { key: true, mono: true, required: true, primary: true }), F('secret', 'password', { key: true, required: true }),
      N('authentication-port', { key: true }), N('accounting-port', { key: true }), D('timeout', { key: true }),
      S('src-address', { advanced: true, mono: true }), S('called-id', { advanced: true }), S('domain', { advanced: true }),
      S('realm', { advanced: true }), I('address', {}), DISABLED, COMMENT],
    commands: ENABLE_DISABLE },
  { path: 'radius/incoming', label: 'RADIUS Incoming', category: 'radius', group: 'Clients', key: true, icon: 'ArrowDownToLine', demoRows: 1,
    fields: [E('accept', ['yes', 'no'], { key: true }), N('port', { key: true }), I('address', { key: true, mono: true }), DISABLED, COMMENT] },
  { path: 'radius/coa', label: 'RADIUS CoA', category: 'radius', group: 'Clients', icon: 'RefreshCw', availability: 'optional', demoRows: 0,
    fields: [I('address', { key: true, mono: true }), N('port', { key: true }), F('secret', 'password'), DISABLED, COMMENT] },
  { path: 'user/aaa', label: 'User AAA', category: 'radius', group: 'Local AAA', kind: 'singleton', key: true, icon: 'ShieldCheck',
    fields: [B('use-radius', { key: true }), B('accounting', { key: true }), D('interim-update'), S('default-group', { key: true }), S('exclude-groups', { advanced: true })],
    commands: [{ id: 'enable', label: 'Enable AAA', icon: 'Power', path: 'enable', target: 'none' }, { id: 'disable', label: 'Disable AAA', icon: 'PowerOff', path: 'disable', target: 'none' }] },
  { path: 'user/active', label: 'Active Users', category: 'radius', group: 'Local AAA', readOnly: true, icon: 'Users', demoRows: 2, hidden: true,
    fields: [NAME, S('address', { key: true }), S('via', { key: true }), S('when', { key: true })] },
];

export const usermanagerEndpoints: EndpointDef[] = [
  { path: 'user-manager/user', label: 'UM Users', category: 'usermanager', group: 'Users', key: true, icon: 'Users', availability: 'v7', demoRows: 8,
    description: 'User Manager 5 (RouterOS 7.10+) accounts.',
    fields: [NAME, F('password', 'password', { key: true }), S('group', { key: true }), S('attributes', { advanced: true }),
      B('disabled', { key: true, tone: 'neutral', boolLabels: ['disabled', 'enabled'] }), COMMENT],
    commands: ENABLE_DISABLE },
  { path: 'user-manager/profile', label: 'UM Profiles', category: 'usermanager', group: 'Profiles', key: true, icon: 'FileCode2', availability: 'v7', demoRows: 4,
    fields: [NAME, S('name-for-users', { key: true }), S('starts-when', { key: true }), S('validity', { key: true }),
      S('price', { advanced: true }), S('override-shared-users', { advanced: true }), S('lock-user', { advanced: true })] },
  { path: 'user-manager/limitation', label: 'UM Limitations', category: 'usermanager', group: 'Profiles', key: true, icon: 'Sliders', availability: 'v7', demoRows: 3,
    fields: [NAME, S('rate-limit-burst-rx', { key: true }), S('rate-limit-rx', { key: true }), S('rate-limit-tx', { key: true }),
      I('uptime-limit', { key: true }), S('transfer-limit', { key: true }), N('download-limit', { advanced: true }), N('upload-limit', { advanced: true })] },
  { path: 'user-manager/profile-limitation', label: 'Profile Limitations', category: 'usermanager', group: 'Profiles', icon: 'Link2', availability: 'v7', demoRows: 3,
    fields: [S('profile', { key: true, primary: true }), S('limitation', { key: true }), B('from-time', { advanced: true }), B('till-time', { advanced: true }), S('weekdays', { advanced: true })] },
  { path: 'user-manager/session', label: 'UM Sessions', category: 'usermanager', group: 'Monitoring', readOnly: true, icon: 'Activity', availability: 'v7', demoRows: 6,
    fields: [NAME, S('user', { key: true }), S('nas-port-id', { key: true }), I('nas-ip-address', { key: true }), D('uptime', { key: true }),
      N('download', { key: true }), N('upload', { key: true }), S('status', { key: true })],
    commands: [{ id: 'remove', label: 'Terminate', icon: 'UserMinus', path: 'remove', target: 'numbers', danger: true, confirm: 'Terminate this session?' }] },
  { path: 'user-manager/router', label: 'UM Routers', category: 'usermanager', group: 'Configuration', icon: 'Server', availability: 'v7', demoRows: 2,
    fields: [NAME, I('address', { key: true }), F('secret', 'password', { key: true }), S('authorize', { key: true }), S('accounting'), N('coa-port', { advanced: true }), DISABLED, COMMENT] },
  { path: 'user-manager/payment', label: 'UM Payments', category: 'usermanager', group: 'Configuration', icon: 'CreditCard', availability: 'optional', demoRows: 0,
    fields: [NAME, S('currency', { key: true }), S('amount', { key: true }), COMMENT] },
  { path: 'user-manager/advanced', label: 'UM Advanced', category: 'usermanager', group: 'Configuration', kind: 'singleton', icon: 'Settings2', availability: 'v7',
    fields: [B('web-interface', { key: true }), N('port', { key: true }), B('tls', { advanced: true }), S('certificate', { advanced: true }), B('paypal-use-sandbox', { advanced: true }), S('paypal-user', { advanced: true })] },
  { path: 'user-manager/user-profile', label: 'User Profiles', category: 'usermanager', group: 'Users', icon: 'Link2', availability: 'v7', demoRows: 5, hidden: true,
    fields: [S('user', { key: true, primary: true }), S('profile', { key: true }), S('start-time', { key: true }), S('end-time', { key: true })] },
  { path: 'user-manager/user-group', label: 'User Groups', category: 'usermanager', group: 'Users', icon: 'Users', availability: 'v7', demoRows: 2, hidden: true,
    fields: [NAME, S('attributes', { key: true })] },
];
