import { B, BY, C, COMMENT, D, DISABLED, E, ENABLE_DISABLE, F, I, N, NAME, ORDERED, S, T, type EndpointDef } from '../types';

/** System, scheduler, logging, accounts, backups, certificates and containers. */

const logTopics = [
  'critical', 'error', 'warning', 'info', 'account', 'async', 'bgp', 'calc', 'caps', 'certificate', 'container', 'dhcp', 'dns',
  'firewall', 'hotspot', 'igmp-proxy', 'interface', 'ipsec', 'l2tp', 'ldp', 'lte', 'manager', 'mpls', 'ospf', 'ovpn', 'ppp',
  'pppoe', 'queue', 'radius', 'raw', 'read', 'rip', 'route', 'script', 'sim', 'snmp', 'ssh', 'store', 'system', 'telephony',
  'tftp', 'web-proxy', 'wireless', 'wireguard', 'write', 'zerotier',
];

export const systemEndpoints: EndpointDef[] = [
  {
    path: 'system/identity', label: 'Identity', category: 'system', group: 'General', kind: 'singleton', key: true, icon: 'BadgeInfo',
    fields: [NAME, S('name', { key: true, primary: true })],
    description: 'The router name — also used as the default hotspot/DNS identity.',
  },
  {
    path: 'system/clock', label: 'Clock', category: 'system', group: 'General', kind: 'singleton', key: true, icon: 'Clock',
    fields: [S('time', { key: true, mono: true }), S('date', { key: true, mono: true }), S('time-zone-name', { key: true }),
      S('time-zone-autodetect', { type: 'boolean', key: true } as any), S('gmt-offset', { key: true, mono: true }),
      S('dst-active', { advanced: true })],
    commands: [
      { id: 'set-time', label: 'Set time (NTP sync)', icon: 'RefreshCw', path: '', target: 'none', body: { 'use-ntp': true }, response: 'json' },
      { id: 'wait-for-ntp', label: 'Sync with NTP server', icon: 'Cloud', path: 'print', target: 'none' },
    ],
  },
  {
    path: 'system/ntp/client', label: 'NTP Client', category: 'system', group: 'General', kind: 'singleton', key: true, icon: 'Clock',
    fields: [B('enabled', { key: true }), E('mode', ['unicast', 'multicast', 'manycast', 'broadcast'], { key: true }),
      S('servers', { key: true, mono: true }), S('server-dns-names', { key: true }), D('freq-drift', { key: true }),
      S('status', { key: true }), S('last-adjustment', { key: true }), S('last-bad-packet', { advanced: true }), N('poll-interval', { advanced: true })],
    commands: [{ id: 'monitor', label: 'Monitoring', icon: 'Activity', path: 'monitor', target: 'none', body: { once: '' }, response: 'json' }],
  },
  { path: 'system/ntp/server', label: 'NTP Server', category: 'system', group: 'General', kind: 'singleton', icon: 'Clock', hidden: true,
    fields: [B('enabled', { key: true }), S('broadcast', { advanced: true }), S('manycast', { advanced: true })] },
  {
    path: 'system/resource', label: 'Resources', category: 'system', group: 'Monitoring', readOnly: true, kind: 'singleton', key: true, icon: 'Cpu',
    description: 'CPU, memory, storage, uptime and RouterOS version.',
    fields: [
      S('version', { key: true, mono: true }), S('board-name', { key: true }), S('architecture-name', { key: true }),
      S('cpu', { key: true }), N('cpu-count', { key: true }), N('cpu-frequency', { key: true, unit: 'MHz' }),
      N('cpu-load', { key: true, unit: '%' }), BY('free-memory', { key: true }), BY('total-memory', { key: true }),
      BY('free-hdd-space', { key: true }), BY('total-hdd-space', { key: true }), D('uptime', { key: true }),
      S('build-time', { advanced: true }), S('factory-software', { advanced: true }), S('platform', { advanced: true }),
      S('license', { advanced: true }), S('cpu-mode', { advanced: true }), N('write-sect-since-reboot', { advanced: true }),
    ],
    live: ['cpu-load', 'free-memory', 'uptime'],
  },
  { path: 'system/health', label: 'Health', category: 'system', group: 'Monitoring', readOnly: true, icon: 'HeartPulse', demoRows: 1,
    description: 'Voltage, temperature, fan and PSU readings (model dependent).',
    fields: [NAME, S('value', { key: true, primary: true }), S('type', { key: true, mono: true })] },
  { path: 'system/routerboard', label: 'Routerboard', category: 'system', group: 'Monitoring', readOnly: true, kind: 'singleton', icon: 'CircuitBoard',
    fields: [S('model', { key: true }), S('serial-number', { key: true, mono: true }), S('firmware-type', { key: true }),
      S('factory-firmware', { key: true }), S('current-firmware', { key: true }), S('upgrade-firmware', { key: true }),
      B('routerboard', { key: true }), S('revision', { advanced: true })],
    commands: [{ id: 'upgrade-firmware', label: 'Upgrade firmware', icon: 'Download', path: 'upgrade-firmware', target: 'none', danger: true, confirm: 'Upgrade routerboard firmware? The router will reboot.' }] },
  { path: 'system/license', label: 'License', category: 'system', group: 'Monitoring', readOnly: true, kind: 'singleton', icon: 'KeySquare', hidden: true,
    fields: [S('software-id', { key: true, mono: true }), S('license-level', { key: true }), S('nlevel', { key: true }), S('deadline', { advanced: true })] },
  { path: 'system/package', label: 'Packages', category: 'system', group: 'Maintenance', readOnly: true, noCreate: true, noEdit: true, icon: 'Package', key: true, demoRows: 8,
    description: 'Installed RouterOS packages and their versions.',
    fields: [NAME, S('version', { key: true, mono: true }), S('scheduled', { key: true }), B('disabled', { key: true, tone: 'neutral', boolLabels: ['disabled', 'enabled'] })],
    commands: [
      { id: 'check-for-updates', label: 'Check for updates', icon: 'RefreshCw', path: 'check-for-updates', target: 'none', response: 'json' },
      { id: 'update', label: 'Install updates', icon: 'Download', path: 'update', target: 'none', danger: true, confirm: 'Download and install RouterOS updates?' },
    ] },
  { path: 'system/routerboard/settings', label: 'Routerboard Settings', category: 'system', group: 'Monitoring', kind: 'singleton', icon: 'Settings2', hidden: true,
    fields: [B('auto-upgrade', { key: true }), S('baud-rate', { advanced: true }), B('boot-device', { advanced: true }), N('boot-delay', { advanced: true }), B('protected-routerboot', { advanced: true }), N('cpu-frequency', { advanced: true }), B('cpu-mode', { advanced: true }), B('silent-boot', { advanced: true })] },
  {
    path: 'system/identity/settings', label: 'Identity Settings', category: 'system', group: 'General', kind: 'singleton', icon: 'BadgeInfo', hidden: true,
    fields: [S('hide-sensitive', { advanced: true }), S('system-name', { advanced: true })],
  },
  {
    path: 'system/scheduler', label: 'Scheduler', category: 'system', group: 'Automation', key: true, icon: 'CalendarClock', demoRows: 6,
    description: 'Time-triggered scripts and system actions.',
    fields: [NAME, S('start-date', { key: true }), S('start-time', { key: true }), S('interval', { key: true }),
      E('on-event', ['script', 'reboot', 'shutdown', 'backup', 'restore', 'check-for-updates', 'restart', 'password', 'leds'], { key: true, primary: true }),
      S('event', { key: true, width: 'lg', mono: true, label: 'Event' }), S('run-count', { key: true }), D('next-run', { key: true }),
      S('policy', { advanced: true }), D('startup-delay', { advanced: true }), DISABLED, COMMENT],
    commands: [...ENABLE_DISABLE, { id: 'run', label: 'Run now', icon: 'Play', path: 'run', target: 'id' }, ...ORDERED],
  },
  {
    path: 'system/script', label: 'Scripts', category: 'system', group: 'Automation', key: true, icon: 'FileCode2', demoRows: 8,
    fields: [NAME, S('source', { type: 'text', key: true, width: 'lg', primary: true, help: 'RouterOS script source.' }),
      S('policy', { key: true }), S('dont-require-permissions', { type: 'boolean', advanced: true } as any),
      S('run-count', { key: true }), S('last-started', { advanced: true }), S('owner', { advanced: true }), COMMENT],
    commands: [{ id: 'run', label: 'Run now', icon: 'Play', path: 'run', target: 'id', response: 'json' }],
  },
  { path: 'system/script/environment', label: 'Script Environment', category: 'system', group: 'Automation', icon: 'Variable', demoRows: 3, hidden: true,
    fields: [NAME, S('value', { key: true, mono: true })] },
  { path: 'system/script/job', label: 'Script Jobs', category: 'system', group: 'Automation', readOnly: true, noCreate: true, noEdit: true, icon: 'ListTree', demoRows: 0, hidden: true,
    fields: [NAME, S('owner', { key: true }), S('started', { key: true }), S('script', { key: true })],
    commands: [{ id: 'kill', label: 'Kill job', icon: 'XCircle', path: 'kill', target: 'numbers', danger: true }] },
  { path: 'system/note', label: 'Note', category: 'system', group: 'General', kind: 'singleton', icon: 'StickyNote', hidden: true, fields: [T('note', { key: true, width: 'lg' })] },
  { path: 'system/watchdog', label: 'Watchdog', category: 'system', group: 'Maintenance', kind: 'singleton', icon: 'Dog',
    fields: [S('watch-address', { key: true, mono: true }), B('automatic-sup-out', { key: true }), B('automatic-sup-out-on-watch-address', { advanced: true }),
      D('watchdog-timer', { key: true }), E('ping-start-after-boot', ['0s', '1m', '5m', '10m'], { advanced: true }),
      S('no-ping-delay', { advanced: true }), B('send-email-to', { advanced: true }), S('ping-timeout', { advanced: true }), B('send-sms-to', { advanced: true })] },
  { path: 'system/ups', label: 'UPS', category: 'system', group: 'Maintenance', kind: 'singleton', icon: 'BatteryCharging',
    fields: [NAME, S('port', { key: true }), S('alarm', { key: true }), E('check-type', ['none', 'simple', 'custom'], { advanced: true }),
      E('mode', ['none', 'standalone'], { advanced: true }), D('on-line', { key: true }), S('alarm-low-battery', { advanced: true }), S('min-runtime', { advanced: true }), D('off-line', { advanced: true })] },
  {
    path: 'system/logging', label: 'Logging Rules', category: 'system', group: 'Logging', key: true, icon: 'FileText', demoRows: 6,
    fields: [F('topics', 'enum', { key: true, primary: true, values: logTopics, help: 'Comma separated topics, prefix with ! to exclude.' }),
      E('action', ['memory', 'disk', 'echo', 'remote', 'webhook', 'syslog', 'console', 'stdout'], { key: true, required: true }),
      S('prefix', { key: true }), D('invalid', { key: true }), DISABLED, COMMENT],
    commands: ENABLE_DISABLE },
  { path: 'system/logging/action', label: 'Log Actions', category: 'system', group: 'Logging', key: true, icon: 'Server', demoRows: 3,
    fields: [NAME, E('target', ['memory', 'disk', 'echo', 'remote', 'webhook', 'syslog', 'console', 'stdout'], { key: true, required: true }),
      S('remote', { key: true, mono: true }), N('remote-port', { key: true }), S('src-address', { advanced: true }), S('syslog-facility', { advanced: true }),
      S('syslog-severity', { advanced: true }), S('syslog-time-format', { advanced: true }), S('disk-file-name', { advanced: true }),
      S('disk-file-count', { advanced: true }), S('disk-lines-per-file', { advanced: true }), B('disk-stop-on-full', { advanced: true }),
      S('memory-lines', { advanced: true }), B('memory-stop-on-full', { advanced: true }), S('webhook-url', { advanced: true }),
      S('ms-chap-format', { advanced: true }), D('interval')] },
  { path: 'log', label: 'Log', category: 'system', group: 'Logging', readOnly: true, noCreate: true, noEdit: true, key: true, icon: 'ScrollText', demoRows: 40,
    description: 'Live system log, newest entries first.',
    fields: [D('time', { key: true, mono: true, width: 'sm', primary: true }), S('topics', { key: true, width: 'sm' }), T('message', { key: true, width: 'lg' })],
    commands: [{ id: 'print', label: 'Refresh', icon: 'RefreshCw', path: 'print', target: 'none', response: 'json' }] },
  {
    path: 'system/user', label: 'Users', category: 'system', group: 'Accounts', key: true, icon: 'UserCog', demoRows: 4,
    description: 'RouterOS login accounts and their groups. Password is never returned by the API.',
    fields: [NAME, S('group', { key: true }), S('address', { key: true, mono: true, help: 'Restrict logins to these source addresses/networks.' }),
      S('last-logged-in', { key: true }), B('disabled', { key: true, tone: 'neutral', boolLabels: ['disabled', 'enabled'] }), COMMENT],
    commands: ENABLE_DISABLE },
  { path: 'system/user/group', label: 'User Groups', category: 'system', group: 'Accounts', key: true, icon: 'ShieldCheck', demoRows: 6,
    fields: [NAME, S('policy', { key: true, width: 'lg', primary: true }), S('system', { advanced: true }), S('skin', { advanced: true }), COMMENT] },
  { path: 'system/user/active', label: 'Active Users', category: 'system', group: 'Accounts', readOnly: true, icon: 'Activity', key: true, demoRows: 3,
    fields: [NAME, S('address', { key: true, mono: true }), S('via', { key: true }), S('when', { key: true }), S('group', { key: true })],
    commands: [{ id: 'remove', label: 'Disconnect', icon: 'UserMinus', path: 'remove', target: 'id', danger: true, confirm: 'Disconnect this user session?' }] },
  { path: 'system/user/aaa', label: 'User AAA', category: 'system', group: 'Accounts', kind: 'singleton', icon: 'ShieldCheck', hidden: true,
    fields: [B('use-radius', { key: true }), B('accounting', { key: true }), S('default-group', { key: true }), D('interim-update')] },
  { path: 'system/user/settings', label: 'User Settings', category: 'system', group: 'Accounts', kind: 'singleton', icon: 'Settings2',
    fields: [S('minimum-password-length', { type: 'number', key: true } as any), B('allow-remote-requests', { key: true }), B('force-password-change', { advanced: true })] },
  { path: 'system/backup', label: 'Backups', category: 'system', group: 'Maintenance', icon: 'HardDriveDownload', demoRows: 3,
    description: 'Binary backups (.backup, full config). Actions: backup / save / load.',
    fields: [NAME, N('size', { key: true, type: 'bytes' } as any), S('creation-time', { key: true })],
    commands: [
      { id: 'backup', label: 'Create backup', icon: 'Save', path: 'backup', target: 'none', params: [{ name: 'name', label: 'File name', type: 'string', default: 'dashboard-backup', required: true }, { name: 'password', label: 'Password (optional)', type: 'password' }], response: 'json' },
      { id: 'save', label: 'Save config', icon: 'Download', path: 'save', target: 'none', params: [{ name: 'name', label: 'File name', type: 'string', default: 'dashboard-config', required: true }], response: 'json' },
      { id: 'load', label: 'Load backup', icon: 'Upload', path: 'load', target: 'none', params: [{ name: 'name', label: 'Backup file', type: 'string', required: true }, { name: 'password', label: 'Password', type: 'password' }], danger: true, confirm: 'Loading a backup replaces configuration and reboots the router. Continue?' },
      { id: 'export', label: 'Export script (.rsc)', icon: 'FileCode2', path: 'export', target: 'none', params: [{ name: 'file', label: 'File name', type: 'string', default: 'dashboard-export' }, { name: 'compact', label: 'Compact', type: 'boolean', default: true }, { name: 'show-sensitive', label: 'Show sensitive', type: 'boolean', default: false }], response: 'json' },
      { id: 'remove', label: 'Delete file', icon: 'Trash2', path: 'remove', target: 'name', danger: true, confirm: 'Delete this file from the router?' },
    ] },
  { path: 'file', label: 'Files', category: 'system', group: 'Maintenance', icon: 'FolderOpen', key: true, demoRows: 14, ordered: true,
    description: 'RouterOS file storage — backups, scripts, packages and logs.',
    fields: [NAME, S('type', { key: true }), BY('size', { key: true, type: 'bytes' } as any), S('creation-time', { key: true }), S('last-modified', { advanced: true }), S('contents', { advanced: true })],
    commands: [...ORDERED,
      { id: 'print-file', label: 'Show contents', icon: 'Eye', path: 'print', target: 'name', body: { file: '${name}' }, response: 'text' },
      { id: 'remove', label: 'Delete', icon: 'Trash2', path: 'remove', target: 'name', danger: true, confirm: 'Delete this file?' }] },
  {
    path: 'system/certificate', label: 'Certificates', category: 'system', group: 'Certificates', key: true, icon: 'FileBadge', demoRows: 4,
    fields: [NAME, S('common-name', { key: true, primary: true }), S('issuer', { key: true }), S('subject', { key: true }),
      S('fingerprint', { key: true, mono: true }), S('key-usage', { advanced: true }), S('serial-number', { advanced: true }),
      S('akid', { advanced: true }), B('expired', { key: true, tone: 'danger' }), S('invalid-before', { advanced: true }), S('invalid-after', { advanced: true }),
      B('ca', { key: true }), B('trusted', { advanced: true }), S('expires-after', { key: true }), COMMENT],
    commands: [
      { id: 'sign', label: 'Sign', icon: 'PenTool', path: 'sign', target: 'id', params: [{ name: 'ca', label: 'CA certificate', type: 'string', required: true }, { name: 'days-valid', label: 'Valid days', type: 'number', default: 365 }], response: 'json' },
      { id: 'import', label: 'Import', icon: 'Upload', path: 'import', target: 'none', params: [{ name: 'file-name', label: 'File name', type: 'string', required: true }, { name: 'passphrase', label: 'Passphrase', type: 'password' }], response: 'json' },
      { id: 'export', label: 'Export', icon: 'Download', path: 'export', target: 'none', params: [{ name: 'file-name', label: 'File name', type: 'string', default: 'cert-export' }], response: 'json' },
      { id: 'create-certificate-request', label: 'Create CSR', icon: 'FilePlus2', path: 'create-certificate-request', target: 'none', params: [{ name: 'name', label: 'Certificate name', type: 'string', required: true }, { name: 'common-name', label: 'Common name', type: 'string', required: true }, { name: 'key-size', label: 'Key size', type: 'enum', values: ['2048', '4096'], default: '2048' }], response: 'json' },
      { id: 'remove', label: 'Remove', icon: 'Trash2', path: 'remove', target: 'id', danger: true, confirm: 'Remove this certificate?' },
    ] },
  { path: 'system/certificate/settings', label: 'Certificate Settings', category: 'system', group: 'Certificates', kind: 'singleton', icon: 'Settings2', hidden: true,
    fields: [S('crl-download', { key: true }), S('crl-store', { key: true }), B('builtin-trust-anchors', { advanced: true }), B('crl-use', { advanced: true })] },
  { path: 'system/snmp', label: 'SNMP', category: 'system', group: 'Services', kind: 'singleton', key: true, icon: 'Radio',
    fields: [B('enabled', { key: true }), B('trap-community', { key: true }), N('trap-version', { key: true }), B('trap-generators', { advanced: true }),
      B('trap-interfaces', { advanced: true }), B('contact', { key: true }), B('location', { key: true }), B('authentication-protocol', { advanced: true }),
      B('encryption-protocol', { advanced: true }), B('engine-id', { advanced: true }), B('v3-authentication-protocol', { advanced: true })],
    commands: [{ id: 'enable', label: 'Enable SNMP', icon: 'Power', path: 'enable', target: 'none' }, { id: 'disable', label: 'Disable SNMP', icon: 'PowerOff', path: 'disable', target: 'none' }] },
  { path: 'system/snmp/community', label: 'SNMP Communities', category: 'system', group: 'Services', icon: 'Users', demoRows: 2,
    fields: [NAME, S('address', { key: true, mono: true }), S('security-options', { key: true }), B('authentication-password', { advanced: true }), B('encryption-password', { advanced: true }), B('read-access', { key: true }), B('write-access', { key: true })] },
  { path: 'system/clock/manual', label: 'Manual Time', category: 'system', group: 'General', kind: 'singleton', icon: 'Clock', hidden: true,
    fields: [S('time', { key: true }), S('date', { key: true })] },
  { path: 'system/console', label: 'Console', category: 'system', group: 'General', kind: 'singleton', icon: 'Terminal', hidden: true,
    fields: [N('line-count', { key: true }), N('columns', { key: true }), S('sanitize-names', { advanced: true }), B('pause-after', { advanced: true })] },
  { path: 'system/device-mode', label: 'Device Mode', category: 'system', group: 'Maintenance', readOnly: true, kind: 'singleton', icon: 'Smartphone', availability: 'v7',
    fields: [S('mode', { key: true, primary: true }), S('container', { key: true }), S('scheduler', { key: true }), S('fetch', { key: true }),
      S('hotspot', { key: true }), S('lte', { key: true }), S('mpls', { key: true }), S('partition', { key: true }), S('romon', { key: true }), S('proxy', { key: true }),
      S('sniffer', { key: true }), S('zerotier', { key: true })],
    commands: [{ id: 'update', label: 'Set device mode', icon: 'ShieldAlert', path: '', target: 'none', params: [{ name: 'mode', label: 'Mode', type: 'enum', values: ['home', 'advanced'], required: true }], danger: true, confirm: 'Changing device mode may restrict features (e.g. containers). Continue?' }] },
  { path: 'system/upgrade', label: 'RouterOS Upgrade', category: 'system', group: 'Maintenance', readOnly: true, kind: 'singleton', icon: 'ArrowUpCircle', hidden: true, fields: [S('installed-version', { key: true }), S('latest-version', { key: true }), S('status', { key: true }), S('channel', { key: true })] },
  { path: 'system/reboot', label: 'Reboot', category: 'system', group: 'Maintenance', kind: 'command', icon: 'Power',
    description: 'Reboot or shut down the device.',
    commands: [
      { id: 'reboot', label: 'Reboot router', path: '', target: 'none', danger: true, confirm: 'Reboot the router now?' },
      { id: 'shutdown', label: 'Shutdown router', path: 'shutdown', target: 'none', danger: true, confirm: 'Shut down the router now?' },
    ] },
  { path: 'system/shutdown', label: 'Shutdown', category: 'system', group: 'Maintenance', kind: 'command', icon: 'PowerOff', hidden: true,
    commands: [{ id: 'shutdown', label: 'Shutdown', path: '', target: 'none', danger: true, confirm: 'Shut down the router now?' }] },
  { path: 'system/reset-configuration', label: 'Reset Configuration', category: 'system', group: 'Maintenance', kind: 'command', icon: 'RotateCcw', hidden: true,
    commands: [{ id: 'reset', label: 'Reset configuration', path: '', target: 'none', params: [{ name: 'keep-users', label: 'Keep users', type: 'boolean', default: false }, { name: 'no-defaults', label: 'No defaults', type: 'boolean', default: false }], danger: true, confirm: 'This wipes the configuration and reboots. Continue?' }] },
];

export const containerEndpoints: EndpointDef[] = [
  {
    path: 'container', label: 'Containers', category: 'containers', group: 'Containers', key: true, icon: 'Boxes', availability: 'v7', demoRows: 4,
    description: 'RouterOS container host: images, networks, mounts, envs and running containers.',
    fields: [
      NAME, S('image', { key: true }), S('interface', { key: true }), S('root-dir', { key: true, mono: true }),
      S('status', { key: true, tone: 'success' }), N('cpu-usage', { key: true, unit: '%' }), BY('memory-usage', { key: true }),
      N('memory-shared', { advanced: true }), S('tag', { advanced: true }), S('arch', { advanced: true }),
      DISABLED, COMMENT,
    ],
    live: ['cpu-usage', 'memory-usage'],
    commands: [...ENABLE_DISABLE,
      { id: 'start', label: 'Start', icon: 'Play', path: 'start', target: 'numbers' },
      { id: 'stop', label: 'Stop', icon: 'Square', path: 'stop', target: 'numbers', danger: true },
      { id: 'killing', label: 'Kill', icon: 'XCircle', path: 'kill', target: 'numbers', danger: true, confirm: 'Force-kill this container?' },
      { id: 'restart', label: 'Restart', icon: 'RotateCw', path: 'restart', target: 'numbers' },
      { id: 'monitor', label: 'Monitor', icon: 'Activity', path: 'monitor', target: 'name', body: { once: '' }, response: 'json' },
      { id: 'restart-image', label: 'Restart container image', icon: 'RefreshCw', path: 'restart-container-image', target: 'numbers', response: 'json' }] },
  { path: 'container/config', label: 'Container Config', category: 'containers', group: 'Configuration', kind: 'singleton', key: true, icon: 'Settings2', availability: 'v7',
    fields: [S('registry-url', { key: true }), S('tmpdir', { key: true, mono: true }), S('ram-high', { key: true }), B('layer-update', { key: true }),
      S('registry-username', { advanced: true }), F('registry-password', 'password', { advanced: true }), N('max-cpu', { advanced: true })] },
  { path: 'container/envs', label: 'Environment Vars', category: 'containers', group: 'Configuration', key: true, icon: 'Variable', availability: 'v7', demoRows: 4,
    fields: [NAME, S('value', { key: true, mono: true }), S('list', { key: true }), DISABLED, COMMENT] },
  { path: 'container/mounts', label: 'Mounts', category: 'containers', group: 'Configuration', key: true, icon: 'HardDrive', availability: 'v7', demoRows: 3,
    fields: [NAME, S('src', { key: true, mono: true }), S('dst', { key: true, mono: true }), S('type', { key: true }), N('read-only', { key: true, type: 'boolean' } as any), DISABLED, COMMENT] },
  { path: 'container/network', label: 'Container Networks', category: 'containers', group: 'Configuration', key: true, icon: 'Network', availability: 'v7', demoRows: 2,
    fields: [NAME, B('gateway', { key: true }), B('dns', { key: true }), S('nat', { key: true }), S('dhcp', { key: true }), S('gateway6', { advanced: true }), DISABLED, COMMENT] },
  { path: 'container/image', label: 'Images', category: 'containers', group: 'Images', readOnly: true, icon: 'Layers', availability: 'v7', demoRows: 5,
    fields: [S('tag', { key: true, primary: true }), S('arch', { key: true }), S('os', { key: true }), S('repo-digest', { key: true, mono: true }), BY('size', { key: true, type: 'bytes' } as any)],
    commands: [{ id: 'pull', label: 'Pull image', icon: 'Download', path: 'pull', target: 'none', params: [{ name: 'image', label: 'Image', type: 'string', required: true, placeholder: 'docker.io/library/alpine' }], response: 'json' },
      { id: 'remove', label: 'Remove image', icon: 'Trash2', path: 'remove', target: 'id', danger: true, confirm: 'Remove this image?' }] },
  { path: 'container/shell', label: 'Container Shell', category: 'containers', group: 'Monitoring', kind: 'command', icon: 'Terminal', availability: 'v7', hidden: true,
    commands: [{ id: 'exec', label: 'Run command', path: '', target: 'numbers', params: [{ name: 'command', label: 'Command', type: 'string', required: true, placeholder: 'sh -c ls /' }], response: 'json' }] },
];

export const iotEndpoints: EndpointDef[] = [
  { path: 'iot/leds', label: 'LEDs', category: 'iot', group: 'GPIO/Serial', readOnly: true, icon: 'Lightbulb', availability: 'v7', demoRows: 4,
    fields: [NAME, S('type', { key: true }), S('status', { key: true }), S('interface', { key: true }), S('gpio', { advanced: true })],
    commands: [{ id: 'set', label: 'Set LED', icon: 'Lightbulb', path: 'set', target: 'none', params: [{ name: 'leds', label: 'LED name', type: 'string', required: true }, { name: 'state', label: 'State', type: 'enum', values: ['on', 'off', 'auto'], required: true }] }] },
  { path: 'iot/gpio', label: 'GPIO', category: 'iot', group: 'GPIO/Serial', icon: 'Cpu', availability: 'v7', demoRows: 3,
    fields: [NAME, B('output', { key: true }), S('input', { key: true }), S('direction', { advanced: true })],
    commands: [{ id: 'set-output', label: 'Set output', icon: 'ToggleRight', path: 'set', target: 'name', params: [{ name: 'value', label: 'Value', type: 'enum', values: ['0', '1'], required: true }] }] },
  { path: 'iot/modbus', label: 'Modbus', category: 'iot', group: 'Modbus', readOnly: true, icon: 'Cpu', availability: 'v7', demoRows: 4,
    fields: [NAME, S('type', { key: true }), S('address', { key: true, mono: true }), S('register', { key: true }), S('value', { key: true, mono: true }), S('timestamp', { advanced: true })] },
  { path: 'iot/mqtt', label: 'MQTT', category: 'iot', group: 'MQTT', icon: 'Radio', availability: 'v7', demoRows: 2,
    fields: [NAME, S('server', { key: true, mono: true }), N('port', { key: true }), S('client-id', { key: true }), S('username', { key: true }),
      F('password', 'password', { key: true }), S('topic', { key: true }), B('keep-alive'), B('auto-connect', { key: true }), DISABLED, COMMENT],
    commands: ENABLE_DISABLE },
  { path: 'iot/mqtt/forwards', label: 'MQTT Forwards', category: 'iot', group: 'MQTT', icon: 'Share2', availability: 'v7', demoRows: 2,
    fields: [NAME, S('mqtt-server', { key: true }), S('topic', { key: true }), S('client-id', { key: true }), S('expanded-topic', { advanced: true }), S('field', { advanced: true }), DISABLED, COMMENT] },
  { path: 'iot/mqtt/subscriptions', label: 'MQTT Subscriptions', category: 'iot', group: 'MQTT', icon: 'ArrowDownToLine', availability: 'v7', demoRows: 2,
    fields: [S('topic', { key: true, primary: true }), S('mqtt-server', { key: true }), S('qos', { key: true }), S('on-message', { key: true, width: 'lg', mono: true }), DISABLED, COMMENT] },
  { path: 'iot/serial', label: 'Serial', category: 'iot', group: 'GPIO/Serial', kind: 'singleton', icon: 'Cable', availability: 'v7', hidden: true,
    fields: [B('enabled', { key: true }), S('baud-rate', { key: true }), S('data-bits', { advanced: true }), S('parity', { advanced: true }), S('stop-bits', { advanced: true }), S('flow-control', { advanced: true })] },
];
