import { B, BY, C, COMMENT, D, DISABLED, E, ENABLE_DISABLE, F, I, N, NAME, S, T, type EndpointDef } from '../types';

/** Diagnostics, monitoring, discovery and automation tools under `/tool`. */

export const toolEndpoints: EndpointDef[] = [
  {
    path: 'tool/ping', label: 'Ping', category: 'tools', group: 'Diagnostics', kind: 'command', key: true, icon: 'Radio',
    description: 'ICMP ping from the router to any host.',
    commands: [{ id: 'ping', label: 'Run ping', path: '', target: 'none', params: [
      { name: 'address', label: 'Address', type: 'ip', required: true, placeholder: '8.8.8.8' },
      { name: 'count', label: 'Count', type: 'number', default: 4 },
      { name: 'size', label: 'Packet size', type: 'number', default: 56 },
      { name: 'interface', label: 'Interface', type: 'string' },
      { name: 'src-address', label: 'Source address', type: 'ip' },
      { name: 'ttl', label: 'TTL', type: 'number', default: 64 },
    ], response: 'json' }],
  },
  {
    path: 'tool/traceroute', label: 'Traceroute', category: 'tools', group: 'Diagnostics', kind: 'command', key: true, icon: 'Route',
    commands: [{ id: 'traceroute', label: 'Run traceroute', path: '', target: 'none', params: [
      { name: 'address', label: 'Address', type: 'ip', required: true, placeholder: '1.1.1.1' },
      { name: 'count', label: 'Max hops', type: 'number', default: 30 },
      { name: 'size', label: 'Packet size', type: 'number', default: 56 },
      { name: 'interface', label: 'Interface', type: 'string' },
      { name: 'src-address', label: 'Source address', type: 'ip' },
    ], response: 'json' }],
  },
  {
    path: 'tool/flood-ping', label: 'Flood Ping', category: 'tools', group: 'Diagnostics', kind: 'command', icon: 'Zap', availability: 'v7',
    commands: [{ id: 'flood-ping', label: 'Run flood ping', path: '', target: 'none', params: [
      { name: 'address', label: 'Address', type: 'ip', required: true }, { name: 'count', label: 'Count', type: 'number', default: 100 },
      { name: 'size', label: 'Packet size', type: 'number', default: 1500 }, { name: 'interface', label: 'Interface', type: 'string' },
    ], response: 'json', danger: true, confirm: 'Flood ping generates high traffic. Continue?' }],
  },
  {
    path: 'tool/bandwidth-test', label: 'Bandwidth Test', category: 'tools', group: 'Throughput', kind: 'command', key: true, icon: 'Gauge',
    description: 'Run a bandwidth test against a local or remote server (requires the bandwidth-server to be enabled on the peer).',
    commands: [{ id: 'run', label: 'Start test', path: '', target: 'none', params: [
      { name: 'address', label: 'Server address', type: 'ip', required: true },
      { name: 'protocol', label: 'Protocol', type: 'enum', values: ['tcp', 'udp'], default: 'tcp' },
      { name: 'direction', label: 'Direction', type: 'enum', values: ['both', 'receive', 'transmit'], default: 'both' },
      { name: 'duration', label: 'Duration', type: 'duration', default: '10s' },
      { name: 'user', label: 'Username', type: 'string' }, { name: 'password', label: 'Password', type: 'password' },
      { name: 'connection-count', label: 'Connection count', type: 'number', default: 20 },
      { name: 'local-tx-speed', label: 'Local TX speed', type: 'string' }, { name: 'random-data', label: 'Random data', type: 'boolean' },
    ], response: 'json' }],
  },
  { path: 'tool/bandwidth-server', label: 'Bandwidth Server', category: 'tools', group: 'Throughput', kind: 'singleton', icon: 'Server', key: true,
    fields: [B('enabled', { key: true }), S('allocate-udp-ports-from', { key: true }), B('authenticate', { key: true }),
      N('max-sessions', { key: true }), S('receive-buffer-size', { advanced: true }), S('send-buffer-size', { advanced: true })],
    commands: [{ id: 'enable', label: 'Enable server', icon: 'Power', path: 'enable', target: 'none' }, { id: 'disable', label: 'Disable server', icon: 'PowerOff', path: 'disable', target: 'none' }] },
  {
    path: 'tool/speed-test', label: 'Speed Test', category: 'tools', group: 'Throughput', kind: 'command', icon: 'Activity', availability: 'v7.14',
    description: 'Built-in speed test to another RouterOS device or the MikroTik test server.',
    commands: [{ id: 'run', label: 'Start speed test', path: '', target: 'none', params: [
      { name: 'address', label: 'Server address', type: 'string', required: true, placeholder: '192.168.88.1' },
      { name: 'direction', label: 'Direction', type: 'enum', values: ['both', 'receive', 'transmit'], default: 'both' },
      { name: 'duration', label: 'Duration', type: 'duration', default: '10s' },
      { name: 'user', label: 'User', type: 'string' }, { name: 'password', label: 'Password', type: 'password' },
    ], response: 'json' }],
  },
  { path: 'tool/sniffer', label: 'Packet Sniffer', category: 'tools', group: 'Monitoring', kind: 'singleton', key: true, icon: 'Radar',
    description: 'Capture traffic to a file on the router or stream it to Wireshark.',
    fields: [S('filter-interface', { key: true }), E('filter-direction', ['any', 'rx', 'tx'], { key: true }), S('filter-ip-address', { key: true }),
      S('filter-protocol', { key: true }), S('filter-port', { key: true }), S('filter-mac-address', { advanced: true }), S('filter-mac-protocol', { advanced: true }),
      S('filter-vlan', { advanced: true }), S('filter-dscp', { advanced: true }), S('filter-broadcast', { advanced: true }),
      B('only-headers', { key: true }), S('file-name', { key: true }), S('file-limit', { key: true }), S('memory-limit', { advanced: true }),
      B('streaming-enabled', { key: true }), S('streaming-server', { key: true }), S('filter-stream', { advanced: true }), S('streaming-port', { advanced: true })],
    commands: [{ id: 'start', label: 'Start sniffing', icon: 'Play', path: 'start', target: 'none', response: 'json' },
      { id: 'stop', label: 'Stop sniffing', icon: 'Square', path: 'stop', target: 'none', response: 'json' }] },
  { path: 'tool/sniffer/quick', label: 'Sniffer Quick', category: 'tools', group: 'Monitoring', kind: 'command', icon: 'Radar', availability: 'v7',
    commands: [{ id: 'quick', label: 'Quick capture', path: '', target: 'none', params: [{ name: 'interface', label: 'Interface', type: 'string' }, { name: 'duration', label: 'Duration', type: 'duration', default: '5s' }], response: 'json' }] },
  { path: 'tool/sniffer/host', label: 'Sniffer Hosts', category: 'tools', group: 'Monitoring', readOnly: true, icon: 'Users', demoRows: 4,
    fields: [I('address', { key: true, primary: true }), S('interface', { key: true }), S('mac-address', { key: true, mono: true }), S('rate', { key: true })] },
  { path: 'tool/sniffer/connection', label: 'Sniffer Connections', category: 'tools', group: 'Monitoring', readOnly: true, icon: 'Activity', demoRows: 4,
    fields: [I('src-address', { key: true }), N('src-port', { key: true }), I('dst-address', { key: true }), N('dst-port', { key: true }), S('protocol', { key: true }), BY('bytes', { key: true }), S('connection-bytes', { key: true })] },
  {
    path: 'tool/torch', label: 'Torch', category: 'tools', group: 'Monitoring', kind: 'command', key: true, icon: 'Flame',
    description: 'Real-time traffic monitor per protocol/port/address.',
    commands: [{ id: 'run', label: 'Start torch', path: '', target: 'none', params: [
      { name: 'interface', label: 'Interface', type: 'string' }, { name: 'duration', label: 'Duration', type: 'duration', default: '5s' },
      { name: 'port', label: 'Port', type: 'string' }, { name: 'src-address', label: 'Source address', type: 'cidr' },
      { name: 'dst-address', label: 'Destination address', type: 'cidr' }, { name: 'protocol', label: 'Protocol', type: 'string' },
      { name: 'mac-address', label: 'MAC address', type: 'mac' }, { name: 'dscp', label: 'DSCP', type: 'string' },
    ], response: 'json' }],
  },
  {
    path: 'tool/fetch', label: 'Fetch', category: 'tools', group: 'Automation', kind: 'command', key: true, icon: 'Download',
    description: 'Download or upload a file / call an HTTP endpoint from the router. Useful to test connectivity and to drive webhooks.',
    commands: [{ id: 'fetch', label: 'Run fetch', path: '', target: 'none', params: [
      { name: 'url', label: 'URL', type: 'string', required: true, placeholder: 'https://example.com/file.txt' },
      { name: 'mode', label: 'Mode', type: 'enum', values: ['http', 'https', 'ftp', 'tftp'], default: 'https' },
      { name: 'dst-path', label: 'Destination path', type: 'string' }, { name: 'user', label: 'User', type: 'string' },
      { name: 'password', label: 'Password', type: 'password' }, { name: 'check-certificate', label: 'Check certificate', type: 'boolean', default: true },
      { name: 'http-method', label: 'HTTP method', type: 'enum', values: ['get', 'post', 'put', 'delete'], default: 'get' },
      { name: 'http-header-field', label: 'HTTP headers', type: 'string', placeholder: 'Content-Type: application/json' },
      { name: 'http-data', label: 'HTTP data', type: 'text' }, { name: 'output', label: 'Output', type: 'enum', values: ['file', 'user', 'none'], default: 'file' },
      { name: 'upload', label: 'Upload (from dst-path)', type: 'boolean' },
    ], response: 'json' }],
  },
  {
    path: 'tool/netwatch', label: 'Netwatch', category: 'tools', group: 'Monitoring', key: true, icon: 'Eye', demoRows: 5,
    description: 'Host availability monitoring with up/down scripts and notifications.',
    fields: [NAME, S('host', { key: true, mono: true, required: true, primary: true }),
      E('type', ['simple', 'icmp', 'arp', 'dns', 'tcp-conn', 'http-get', 'https-get'], { key: true, default: 'icmp' }),
      D('interval', { key: true, default: '1m' }), D('timeout', { key: true }), N('port', { key: true }), S('http-code', { key: true }),
      S('status', { key: true }), D('since', { key: true }), S('up-script', { key: true }), S('down-script', { key: true }),
      S('up-script', { key: true }), B('test-script', { advanced: true }), D('thr-max', { advanced: true }), DISABLED, COMMENT],
    commands: [...ENABLE_DISABLE,
      { id: 'test', label: 'Run test', icon: 'Play', path: 'set', target: 'id', params: [{ name: 'host', label: 'Host', type: 'string', required: true }], response: 'json' }] },
  { path: 'tool/netwatch/undefined', label: 'Netwatch (legacy)', category: 'tools', group: 'Monitoring', hidden: true, demoRows: 0, fields: [NAME, S('host', { key: true })], availability: 'optional' },
  { path: 'tool/graphing', label: 'Graphing', category: 'tools', group: 'Monitoring', kind: 'singleton', icon: 'LineChart', key: true,
    fields: [B('enabled', { key: true }), S('store-every', { key: true }), N('page-refresh', { key: true })],
    commands: [{ id: 'enable', label: 'Enable graphing', icon: 'Power', path: 'enable', target: 'none' }, { id: 'disable', label: 'Disable graphing', icon: 'PowerOff', path: 'disable', target: 'none' }] },
  { path: 'tool/graphing/interface', label: 'Graph Interfaces', category: 'tools', group: 'Monitoring', icon: 'Cable', key: true, demoRows: 4,
    fields: [S('interface', { key: true, primary: true }), S('allow-address', { key: true }), S('allow-target', { advanced: true }), DISABLED, COMMENT] },
  { path: 'tool/graphing/resource', label: 'Graph Resource', category: 'tools', group: 'Monitoring', icon: 'Cpu', demoRows: 1,
    fields: [S('allow-address', { key: true }), S('allow-target', { advanced: true }), DISABLED, COMMENT] },
  { path: 'tool/graphing/queue', label: 'Graph Queues', category: 'tools', group: 'Monitoring', icon: 'Gauge', demoRows: 4,
    fields: [S('queue', { key: true, primary: true }), S('allow-address', { key: true }), S('allow-target', { advanced: true }), DISABLED, COMMENT] },
  { path: 'tool/sms', label: 'SMS', category: 'tools', group: 'Notifications', kind: 'singleton', icon: 'MessageSquare', key: true,
    fields: [N('port', { key: true }), B('secret', { key: true }), B('notify-on-receive', { key: true }), S('send-sms-to', { advanced: true }), S('report-command', { advanced: true })],
    commands: [{ id: 'send', label: 'Send SMS', icon: 'Send', path: 'send', target: 'none', params: [{ name: 'port', label: 'Port', type: 'string' }, { name: 'phone-number', label: 'Phone number', type: 'string', required: true }, { name: 'message', label: 'Message', type: 'text', required: true }], response: 'json' }] },
  { path: 'tool/sms/inbox', label: 'SMS Inbox', category: 'tools', group: 'Notifications', readOnly: true, icon: 'Inbox', demoRows: 3,
    fields: [S('phone', { key: true, primary: true }), T('message', { key: true, width: 'lg' }), S('timestamp', { key: true }), S('type', { key: true })] },
  { path: 'tool/email', label: 'Email', category: 'tools', group: 'Notifications', kind: 'singleton', icon: 'Mail', key: true,
    fields: [S('from', { key: true }), S('server', { key: true, mono: true }), N('port', { key: true }), B('start-tls', { key: true }),
      B('tls', { key: true }), S('user', { key: true }), F('password', 'password', { key: true }), B('auth', { advanced: true })],
    commands: [{ id: 'send', label: 'Send test email', icon: 'Send', path: 'send', target: 'none', params: [
      { name: 'to', label: 'To', type: 'string', required: true }, { name: 'subject', label: 'Subject', type: 'string', default: 'RouterOS test' },
      { name: 'body', label: 'Body', type: 'text', default: 'Test message from the RouterOS dashboard.' }], response: 'json' }] },
  { path: 'tool/dns-update', label: 'Dynamic DNS Update', category: 'tools', group: 'Automation', icon: 'Globe2', availability: 'v7', demoRows: 2,
    fields: [NAME, S('dns-server', { key: true, mono: true }), S('address', { key: true, mono: true }), S('key', { key: true, mono: true }),
      S('key-name', { key: true }), S('ttl', { key: true }), DISABLED, COMMENT],
    commands: [{ id: 'update', label: 'Force update', icon: 'RefreshCw', path: 'update', target: 'id', response: 'json' }] },
  { path: 'tool/mac-server', label: 'MAC Server', category: 'tools', group: 'Discovery', kind: 'singleton', icon: 'Network',
    fields: [S('allowed-interface-list', { key: true }), S('interfaces', { advanced: true }), B('protocol', { advanced: true })] },
  { path: 'tool/mac-server/mac-winbox', label: 'MAC WinBox', category: 'tools', group: 'Discovery', icon: 'MonitorSmartphone', demoRows: 2,
    fields: [S('interface', { key: true }), S('allowed-interface-list', { advanced: true }), B('disabled', { key: true, tone: 'neutral', boolLabels: ['disabled', 'enabled'] })] },
  { path: 'tool/mac-server/ping', label: 'MAC Ping Server', category: 'tools', group: 'Discovery', icon: 'Radio', demoRows: 2,
    fields: [S('interface', { key: true }), S('allowed-interface-list', { advanced: true }), B('disabled', { key: true, tone: 'neutral', boolLabels: ['disabled', 'enabled'] })] },
  { path: 'tool/romon', label: 'RoMON', category: 'tools', group: 'Discovery', kind: 'singleton', icon: 'Network', key: true,
    fields: [B('enabled', { key: true }), F('secret', 'password', { key: true }), N('port', { key: true }), B('idle-timeout', { advanced: true })],
    commands: [{ id: 'discover', label: 'Discover neighbours', icon: 'Radar', path: 'discover', target: 'none', body: { once: '' }, response: 'json' }] },
  { path: 'tool/romon/port', label: 'RoMON Ports', category: 'tools', group: 'Discovery', icon: 'Plug', demoRows: 2, hidden: true,
    fields: [S('interface', { key: true, primary: true }), B('forbid', { key: true }), F('secret', 'password'), N('cost', { advanced: true }), DISABLED, COMMENT] },
  { path: 'tool/macscan', label: 'MAC Scan', category: 'tools', group: 'Discovery', readOnly: true, noCreate: true, noEdit: true, icon: 'Radar', demoRows: 6,
    description: 'Scan the local subnet for MAC addresses of neighbours.',
    fields: [{ name: 'mac-address', type: 'mac', label: 'MAC', key: true, mono: true, primary: true }, S('address', { key: true, mono: true }), S('interface', { key: true }), S('age', { key: true })],
    commands: [{ id: 'scan', label: 'Start scan', icon: 'Play', path: '', target: 'none', params: [{ name: 'interface', label: 'Interface', type: 'string', required: true }, { name: 'duration', label: 'Duration', type: 'duration', default: '10s' }], response: 'json' }] },
  { path: 'tool/ip-scan', label: 'IP Scan', category: 'tools', group: 'Discovery', readOnly: true, noCreate: true, noEdit: true, icon: 'Search', demoRows: 8,
    fields: [I('address', { key: true, mono: true, primary: true }), S('mac-address', { key: true, mono: true }), S('interface', { key: true }), D('timeout', { key: true }), S('seq', { key: true })],
    commands: [{ id: 'scan', label: 'Start scan', icon: 'Play', path: '', target: 'none', params: [{ name: 'address', label: 'Address range', type: 'cidr', required: true, default: '192.168.88.0/24' }, { name: 'interface', label: 'Interface', type: 'string' }, { name: 'duration', label: 'Duration', type: 'duration', default: '10s' }], response: 'json' }] },
  { path: 'tool/wol', label: 'Wake on LAN', category: 'tools', group: 'Diagnostics', kind: 'command', icon: 'Sunrise',
    commands: [{ id: 'wol', label: 'Send magic packet', path: '', target: 'none', params: [{ name: 'mac', label: 'MAC address', type: 'mac', required: true }, { name: 'interface', label: 'Interface', type: 'string', required: true }], response: 'json' }] },
  { path: 'tool/profile', label: 'Profiler', category: 'tools', group: 'Diagnostics', readOnly: true, noCreate: true, noEdit: true, icon: 'Gauge', demoRows: 8,
    description: 'CPU profiler — samples where the router spends its CPU time.',
    fields: [NAME, S('usage', { key: true, primary: true }), S('cpu', { key: true }), S('percent', { key: true })],
    commands: [{ id: 'run', label: 'Run profiler', icon: 'Play', path: '', target: 'none', params: [{ name: 'duration', label: 'Duration', type: 'duration', default: '5s' }, { name: 'cpu', label: 'CPU', type: 'string' }], response: 'json' }] },
  { path: 'tool/traffic-generator', label: 'Traffic Generator', category: 'tools', group: 'Throughput', kind: 'singleton', icon: 'TestTube', availability: 'v7.16',
    fields: [B('latency-distribution', { key: true }), S('stats-interval', { advanced: true })] },
  { path: 'tool/traffic-generator/port', label: 'TG Ports', category: 'tools', group: 'Throughput', icon: 'Plug', availability: 'v7.16', demoRows: 2,
    fields: [S('interface', { key: true, primary: true }), S('tx-template', { key: true }), S('rx-template', { key: true }), B('disabled', { key: true, tone: 'neutral', boolLabels: ['disabled', 'enabled'] }), COMMENT] },
  { path: 'tool/traffic-generator/stream', label: 'TG Streams', category: 'tools', group: 'Throughput', icon: 'Waves', availability: 'v7.16', demoRows: 2,
    fields: [NAME, S('tx-template', { key: true }), S('packet-size', { key: true }), S('rate', { key: true }), S('tx-port', { advanced: true }), S('rx-port', { advanced: true }), DISABLED, COMMENT] },
  { path: 'tool/traffic-generator/packet-template', label: 'TG Packet Templates', category: 'tools', group: 'Throughput', icon: 'Layers', availability: 'v7.16', demoRows: 2,
    fields: [NAME, S('headers', { key: true, mono: true }), S('payload', { advanced: true }), N('extra-bytes', { advanced: true }), COMMENT] },
  { path: 'tool/traffic-generator/stats', label: 'TG Stats', category: 'tools', group: 'Throughput', readOnly: true, icon: 'Activity', availability: 'v7.16', demoRows: 2,
    fields: [NAME, S('tx-packet', { key: true }), S('rx-packet', { key: true }), S('tx-rate', { key: true }), S('rx-rate', { key: true }), S('latency', { key: true }), S('jitter', { key: true })] },
  { path: 'tool/keygen', label: 'Key Generator', category: 'tools', group: 'Automation', kind: 'command', icon: 'KeyRound', hidden: true,
    commands: [{ id: 'keygen', label: 'Generate key', path: '', target: 'none', params: [{ name: 'key-size', label: 'Key size', type: 'enum', values: ['1024', '2048', '4096'], default: '2048' }], response: 'json' }] },
  { path: 'dude', label: 'The Dude', category: 'tools', group: 'Discovery', kind: 'singleton', icon: 'Search', availability: 'optional',
    fields: [B('enabled', { key: true }), S('data-directory', { key: true }), S('status', { key: true })] },
];

/** Raw command surfaces exposed outside `/tool`. */
export const commandEndpoints: EndpointDef[] = [
  { path: 'execute', label: 'Console Command', category: 'tools', group: 'Console', kind: 'command', key: true, icon: 'Terminal',
    description: 'Run any RouterOS console command as a one-off script. Output is returned as JSON.',
    commands: [{ id: 'execute', label: 'Execute', path: '', target: 'none', params: [{ name: 'script', label: 'Command', type: 'text', required: true, placeholder: ':put [/system/resource/get version]' }], response: 'json', danger: true, confirm: 'Run this command on the router?' }] },
  { path: 'export', label: 'Export Configuration', category: 'tools', group: 'Console', kind: 'command', key: true, icon: 'FileCode2',
    commands: [{ id: 'export', label: 'Export', path: '', target: 'none', params: [
      { name: 'file', label: 'File name', type: 'string', default: 'config-export' },
      { name: 'compact', label: 'Compact', type: 'boolean', default: true },
      { name: 'show-sensitive', label: 'Show sensitive', type: 'boolean', default: false }], response: 'json' }] },
  { path: 'system/script/run', label: 'Run Script', category: 'tools', group: 'Console', kind: 'command', icon: 'Play', hidden: true,
    commands: [{ id: 'run', label: 'Run script', path: '', target: 'id', params: [{ name: '.id', label: 'Script ID', type: 'string', required: true }], response: 'json' }] },
];
