import fs from 'node:fs';
import path from 'node:path';
import * as lucide from 'lucide-react';

const names = new Set(Object.keys(lucide).filter(k => /^[A-Z][A-Za-z0-9]*$/.test(k)));
const files = [];
const walk = (dir) => {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p);
    else if (/\.(ts|tsx)$/.test(e.name)) files.push(p);
  }
};
for (const d of ['src', 'shared']) walk(d);

const used = new Set();
for (const f of files) {
  const text = fs.readFileSync(f, 'utf8');
  for (const m of text.matchAll(/['"]([A-Z][A-Za-z0-9]*)['"]/g)) {
    if (names.has(m[1])) used.add(m[1]);
  }
  for (const m of text.matchAll(/lucide-react['"]\)?\s*;?/g)) { /* no-op */ }
}
// Icons referenced directly as members of the wildcard namespace.
for (const f of files) {
  const text = fs.readFileSync(f, 'utf8');
  for (const m of text.matchAll(/LucideIcons\.([A-Za-z0-9]+)/g)) used.add(m[1]);
}
used.add('Dot');

const list = [...used].sort();
const body = list.map(n => `  ${n},`).join('\n');
const out = `// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// Explicit imports keep lucide-react tree-shakeable: importing the whole
// namespace pulled ~1 MB of unused icons into the main bundle.
import {
${body}
} from 'lucide-react';

export {
${list.map(n => `  ${n},`).join('\n')}
};

export const icons: Record<string, React.ComponentType<any>> = {
${list.map(n => `  ${n},`).join('\n')}
};
`;
fs.writeFileSync('src/components/iconRegistry.tsx', `import type React from 'react';\n\n${out}`);
console.log(`registered ${list.length} icons`);
